/* 16:05:23 root@directorzone.local */ SELECT * FROM `user` ORDER BY `userid` LIMIT 0,1000;
/* 16:05:25 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:05:25 root@directorzone.local */ SHOW VARIABLES LIKE 'collation_database';
/* 16:06:11 root@directorzone.local */ SET NAMES 'utf8';
/* 16:06:11 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availability';
/* 16:06:11 root@directorzone.local */ SHOW CREATE TABLE `availability`;
/* 16:06:11 root@directorzone.local */ SET NAMES 'latin1';
/* 16:06:11 root@directorzone.local */ SHOW INDEX FROM `availability`;
/* 16:06:11 root@directorzone.local */ SELECT COUNT(1) FROM `availability`;
/* 16:06:12 root@directorzone.local */ SELECT * FROM `availability` LIMIT 0,1000;
/* 16:06:24 root@directorzone.local */ SET NAMES 'utf8';
/* 16:06:24 root@directorzone.local */ SHOW TABLE STATUS LIKE 'userlanguage';
/* 16:06:24 root@directorzone.local */ SHOW CREATE TABLE `userlanguage`;
/* 16:06:24 root@directorzone.local */ SET NAMES 'latin1';
/* 16:06:24 root@directorzone.local */ SHOW INDEX FROM `userlanguage`;
/* 16:06:25 root@directorzone.local */ SELECT COUNT(1) FROM `userlanguage`;
/* 16:06:25 root@directorzone.local */ SET NAMES 'utf8';
/* 16:06:25 root@directorzone.local */ SHOW TABLE STATUS LIKE 'userprofessionalqualification';
/* 16:06:25 root@directorzone.local */ SHOW CREATE TABLE `userprofessionalqualification`;
/* 16:06:25 root@directorzone.local */ SET NAMES 'latin1';
/* 16:06:25 root@directorzone.local */ SHOW INDEX FROM `userprofessionalqualification`;
/* 16:06:25 root@directorzone.local */ SELECT COUNT(1) FROM `userprofessionalqualification`;
/* 16:06:27 root@directorzone.local */ SET NAMES 'utf8';
/* 16:06:27 root@directorzone.local */ SHOW TABLE STATUS LIKE 'usertargetrole';
/* 16:06:27 root@directorzone.local */ SHOW CREATE TABLE `usertargetrole`;
/* 16:06:27 root@directorzone.local */ SET NAMES 'latin1';
/* 16:06:27 root@directorzone.local */ SHOW INDEX FROM `usertargetrole`;
/* 16:06:27 root@directorzone.local */ SELECT COUNT(1) FROM `usertargetrole`;
/* 16:06:29 root@directorzone.local */ SET NAMES 'utf8';
/* 16:06:29 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:06:29 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:06:29 root@directorzone.local */ SET NAMES 'latin1';
/* 16:06:29 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:06:29 root@directorzone.local */ SELECT COUNT(1) FROM `user`;
/* 16:06:36 root@directorzone.local */ ALTER TABLE `user` DROP FOREIGN KEY `user_ibfk_6`;
/* 16:06:36 root@directorzone.local */ ALTER TABLE `user` DROP `availabilityid`;
/* 16:06:36 root@directorzone.local */ SET NAMES 'utf8';
/* 16:06:36 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:06:36 root@directorzone.local */ SET NAMES 'latin1';
/* 16:06:36 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:06:36 root@directorzone.local */ SET NAMES 'utf8';
/* 16:06:36 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:06:36 root@directorzone.local */ SET NAMES 'latin1';
/* 16:06:38 root@directorzone.local */ SET NAMES 'utf8';
/* 16:06:38 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availability';
/* 16:06:38 root@directorzone.local */ SHOW CREATE TABLE `availability`;
/* 16:06:38 root@directorzone.local */ SET NAMES 'latin1';
/* 16:06:38 root@directorzone.local */ SHOW INDEX FROM `availability`;
/* 16:06:38 root@directorzone.local */ SELECT COUNT(1) FROM `availability`;
/* 16:06:42 root@directorzone.local */ DROP TABLE `availability`;
/* 16:06:44 root@directorzone.local */ SET NAMES 'utf8';
/* 16:06:44 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:06:44 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:06:44 root@directorzone.local */ SET NAMES 'latin1';
/* 16:06:44 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:06:44 root@directorzone.local */ SELECT COUNT(1) FROM `user`;
/* 16:11:30 root@directorzone.local */ ALTER TABLE `user` ADD `speakertopics` TEXT  NULL  AFTER `whoswhosectorid`;
/* 16:11:30 root@directorzone.local */ SET NAMES 'utf8';
/* 16:11:30 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:11:30 root@directorzone.local */ SET NAMES 'latin1';
/* 16:11:30 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:11:30 root@directorzone.local */ SET NAMES 'utf8';
/* 16:11:30 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:11:30 root@directorzone.local */ SET NAMES 'latin1';
/* 16:11:30 root@directorzone.local */ SET NAMES 'utf8';
/* 16:11:30 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availableas';
/* 16:11:30 root@directorzone.local */ SHOW CREATE TABLE `availableas`;
/* 16:11:30 root@directorzone.local */ SET NAMES 'latin1';
/* 16:11:30 root@directorzone.local */ SHOW INDEX FROM `availableas`;
/* 16:11:31 root@directorzone.local */ SELECT COUNT(1) FROM `availableas`;
/* 16:11:31 root@directorzone.local */ SELECT * FROM `availableas` LIMIT 0,1000;
/* 16:11:54 root@directorzone.local */ SET NAMES 'utf8';
/* 16:11:54 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:11:54 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:11:54 root@directorzone.local */ SET NAMES 'latin1';
/* 16:11:54 root@directorzone.local */ SELECT * FROM `user` LIMIT 0,1000;
/* 16:11:55 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:06 root@directorzone.local */ ALTER TABLE `user` ADD `availableasspokesperson` INT  NULL  DEFAULT NULL  AFTER `speakertopics`;
/* 16:12:06 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:06 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:06 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:06 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:06 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:06 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:06 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:12 root@directorzone.local */ ALTER TABLE `user` ADD `availableasspeaker` INT  NULL  DEFAULT NULL  AFTER `availableasspokesperson`;
/* 16:12:12 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:12 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:12 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:12 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:12 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:12 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:12 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:19 root@directorzone.local */ ALTER TABLE `user` ADD `availableasexpertwitness` INT  NULL  DEFAULT NULL  AFTER `availableasspeaker`;
/* 16:12:19 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:19 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:19 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:19 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:19 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:19 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:19 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:24 root@directorzone.local */ ALTER TABLE `user` CHANGE `availableasspokesperson` `availableasspokesperson` CHAR(11)  NULL  DEFAULT NULL;
/* 16:12:24 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:24 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:24 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:24 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:24 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:24 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:24 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:25 root@directorzone.local */ ALTER TABLE `user` CHANGE `availableasspeaker` `availableasspeaker` CHAR(11)  NULL  DEFAULT NULL;
/* 16:12:25 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:25 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:25 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:25 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:25 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:25 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:25 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:27 root@directorzone.local */ ALTER TABLE `user` CHANGE `availableasexpertwitness` `availableasexpertwitness` CHAR(11)  NULL  DEFAULT NULL;
/* 16:12:27 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:27 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:27 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:27 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:27 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:27 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:27 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:28 root@directorzone.local */ ALTER TABLE `user` CHANGE `availableasspokesperson` `availableasspokesperson` CHAR(1)  CHARACTER SET latin1  COLLATE latin1_swedish_ci  NULL  DEFAULT NULL;
/* 16:12:28 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:28 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:28 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:28 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:28 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:28 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:28 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:29 root@directorzone.local */ ALTER TABLE `user` CHANGE `availableasspeaker` `availableasspeaker` CHAR(1)  CHARACTER SET latin1  COLLATE latin1_swedish_ci  NULL  DEFAULT NULL;
/* 16:12:29 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:29 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:29 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:29 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:29 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:29 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:29 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:31 root@directorzone.local */ ALTER TABLE `user` CHANGE `availableasexpertwitness` `availableasexpertwitness` CHAR(1)  CHARACTER SET latin1  COLLATE latin1_swedish_ci  NULL  DEFAULT NULL;
/* 16:12:31 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:31 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:31 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:31 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:31 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:31 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:31 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:33 root@directorzone.local */ ALTER TABLE `user` CHANGE `availableasspokesperson` `availableasspokesperson` CHAR(1)  CHARACTER SET latin1  COLLATE latin1_swedish_ci  NULL  DEFAULT 'N';
/* 16:12:33 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:33 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:33 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:33 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:33 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:33 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:33 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:34 root@directorzone.local */ ALTER TABLE `user` CHANGE `availableasspeaker` `availableasspeaker` CHAR(1)  CHARACTER SET latin1  COLLATE latin1_swedish_ci  NULL  DEFAULT 'N';
/* 16:12:34 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:34 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:34 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:34 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:34 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:34 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:34 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:35 root@directorzone.local */ ALTER TABLE `user` CHANGE `availableasexpertwitness` `availableasexpertwitness` CHAR(1)  CHARACTER SET latin1  COLLATE latin1_swedish_ci  NULL  DEFAULT 'N';
/* 16:12:35 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:35 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:12:35 root@directorzone.local */ SET NAMES 'latin1';
/* 16:12:35 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:12:35 root@directorzone.local */ SET NAMES 'utf8';
/* 16:12:35 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:12:35 root@directorzone.local */ SET NAMES 'latin1';
/* 16:37:17 root@directorzone.local */ SET NAMES 'utf8';
/* 16:37:17 root@directorzone.local */ SHOW TABLE STATUS LIKE 'usertargetrole';
/* 16:37:17 root@directorzone.local */ SHOW CREATE TABLE `usertargetrole`;
/* 16:37:17 root@directorzone.local */ SET NAMES 'latin1';
/* 16:37:17 root@directorzone.local */ SHOW INDEX FROM `usertargetrole`;
/* 16:37:17 root@directorzone.local */ SELECT COUNT(1) FROM `usertargetrole`;
/* 16:37:31 root@directorzone.local */ SHOW VARIABLES LIKE 'default_storage_engine';
/* 16:37:40 root@directorzone.local */ SET NAMES 'utf8';
/* 16:37:40 root@directorzone.local */ CREATE TABLE `userwhoswhosector` (id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT);
/* 16:37:40 root@directorzone.local */ SHOW TABLE STATUS LIKE 'userwhoswhosector';
/* 16:37:40 root@directorzone.local */ SHOW CREATE TABLE `userwhoswhosector`;
/* 16:37:40 root@directorzone.local */ SET NAMES 'latin1';
/* 16:37:40 root@directorzone.local */ SHOW INDEX FROM `userwhoswhosector`;
/* 16:37:40 root@directorzone.local */ SELECT COUNT(1) FROM `userwhoswhosector`;
/* 16:37:50 root@directorzone.local */ ALTER TABLE `userwhoswhosector` CHANGE `id` `userwhoswhosectorid` INT(11)  UNSIGNED  NOT NULL  AUTO_INCREMENT;
/* 16:37:50 root@directorzone.local */ SET NAMES 'utf8';
/* 16:37:50 root@directorzone.local */ SHOW CREATE TABLE `userwhoswhosector`;
/* 16:37:50 root@directorzone.local */ SET NAMES 'latin1';
/* 16:37:50 root@directorzone.local */ SHOW INDEX FROM `userwhoswhosector`;
/* 16:37:50 root@directorzone.local */ SET NAMES 'utf8';
/* 16:37:50 root@directorzone.local */ SHOW TABLE STATUS LIKE 'userwhoswhosector';
/* 16:37:50 root@directorzone.local */ SET NAMES 'latin1';
/* 16:37:53 root@directorzone.local */ ALTER TABLE `userwhoswhosector` ADD `userid` INT  NULL  DEFAULT NULL  AFTER `userwhoswhosectorid`;
/* 16:37:53 root@directorzone.local */ SET NAMES 'utf8';
/* 16:37:53 root@directorzone.local */ SHOW CREATE TABLE `userwhoswhosector`;
/* 16:37:53 root@directorzone.local */ SET NAMES 'latin1';
/* 16:37:53 root@directorzone.local */ SHOW INDEX FROM `userwhoswhosector`;
/* 16:37:53 root@directorzone.local */ SET NAMES 'utf8';
/* 16:37:53 root@directorzone.local */ SHOW TABLE STATUS LIKE 'userwhoswhosector';
/* 16:37:53 root@directorzone.local */ SET NAMES 'latin1';
/* 16:37:59 root@directorzone.local */ ALTER TABLE `userwhoswhosector` ADD `sectorid` INT(11)  NULL  DEFAULT NULL  AFTER `userid`;
/* 16:37:59 root@directorzone.local */ SET NAMES 'utf8';
/* 16:37:59 root@directorzone.local */ SHOW CREATE TABLE `userwhoswhosector`;
/* 16:37:59 root@directorzone.local */ SET NAMES 'latin1';
/* 16:37:59 root@directorzone.local */ SHOW INDEX FROM `userwhoswhosector`;
/* 16:37:59 root@directorzone.local */ SET NAMES 'utf8';
/* 16:37:59 root@directorzone.local */ SHOW TABLE STATUS LIKE 'userwhoswhosector';
/* 16:37:59 root@directorzone.local */ SET NAMES 'latin1';
/* 16:41:48 root@directorzone.local */ SET NAMES 'utf8';
/* 16:41:48 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:41:48 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:41:48 root@directorzone.local */ SET NAMES 'latin1';
/* 16:41:48 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 16:41:48 root@directorzone.local */ SELECT COUNT(1) FROM `user`;
/* 16:41:56 root@directorzone.local */ ALTER TABLE `user` DROP `whoswhosectorid`;
/* 16:41:56 root@directorzone.local */ SET NAMES 'utf8';
/* 16:41:56 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 16:41:56 root@directorzone.local */ SET NAMES 'latin1';
/* 16:41:56 root@directorzone.local */ SET NAMES 'utf8';
/* 16:41:56 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 16:41:56 root@directorzone.local */ SET NAMES 'latin1';
/* 16:41:56 root@directorzone.local */ SHOW INDEX FROM `user`;
