/* 21:58:22 root@directorzone.local */ SHOW VARIABLES;
/* 21:58:22 root@directorzone.local */ SELECT @@global.max_allowed_packet;
/* 21:58:22 root@directorzone.local */ SHOW DATABASES;
/* 21:58:25 root@directorzone.local */ USE `directorzone_zf2`;
/* 21:58:25 root@directorzone.local */ SHOW VARIABLES LIKE 'character_set_database';
/* 21:58:25 root@directorzone.local */ SHOW /*!50002 FULL*/ TABLES;
/* 21:58:25 root@directorzone.local */ SELECT * FROM information_schema.routines WHERE routine_schema = 'directorzone_zf2' ORDER BY routine_name;
/* 21:58:30 root@directorzone.local */ SHOW TABLE STATUS LIKE 'companydirectory';
/* 21:58:30 root@directorzone.local */ SHOW CREATE TABLE `companydirectory`;
/* 21:58:30 root@directorzone.local */ SET NAMES 'latin1';
/* 21:58:30 root@directorzone.local */ SELECT * FROM `companydirectory` LIMIT 0,1000;
/* 21:58:31 root@directorzone.local */ SHOW TABLES IN information_schema LIKE 'ENGINES';
/* 21:58:31 root@directorzone.local */ SELECT Engine, Support FROM `information_schema`.`engines` WHERE SUPPORT IN ('DEFAULT', 'YES');
/* 21:58:31 root@directorzone.local */ SELECT * FROM `information_schema`.`character_sets` ORDER BY `character_set_name` ASC;
/* 21:58:31 root@directorzone.local */ SELECT * FROM `information_schema`.`collations` WHERE character_set_name = 'latin1' ORDER BY `collation_name` ASC;
/* 21:58:38 root@directorzone.local */ SHOW INDEX FROM `companydirectory`;
/* 21:58:38 root@directorzone.local */ SHOW VARIABLES LIKE 'collation_database';
/* 21:58:42 root@directorzone.local */ SET NAMES 'utf8';
/* 21:58:42 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 21:58:42 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 21:58:42 root@directorzone.local */ SET NAMES 'latin1';
/* 21:58:42 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 21:58:42 root@directorzone.local */ SELECT COUNT(1) FROM `user`;
/* 21:59:30 root@directorzone.local */ SET NAMES 'utf8';
/* 21:59:30 root@directorzone.local */ SHOW TABLE STATUS LIKE 'companyofficer';
/* 21:59:30 root@directorzone.local */ SHOW CREATE TABLE `companyofficer`;
/* 21:59:30 root@directorzone.local */ SET NAMES 'latin1';
/* 21:59:30 root@directorzone.local */ SHOW INDEX FROM `companyofficer`;
/* 21:59:30 root@directorzone.local */ SELECT COUNT(1) FROM `companyofficer`;
/* 22:04:18 root@directorzone.local */ SET NAMES 'utf8';
/* 22:04:18 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availability';
/* 22:04:18 root@directorzone.local */ SHOW CREATE TABLE `availability`;
/* 22:04:18 root@directorzone.local */ SET NAMES 'latin1';
/* 22:04:18 root@directorzone.local */ SHOW INDEX FROM `availability`;
/* 22:04:18 root@directorzone.local */ SELECT COUNT(1) FROM `availability`;
/* 22:04:19 root@directorzone.local */ SELECT * FROM `availability` LIMIT 0,1000;
/* 22:06:03 root@directorzone.local */ SET NAMES 'utf8';
/* 22:06:03 root@directorzone.local */ SHOW TABLE STATUS LIKE 'useravailableas';
/* 22:06:03 root@directorzone.local */ SHOW CREATE TABLE `useravailableas`;
/* 22:06:03 root@directorzone.local */ SET NAMES 'latin1';
/* 22:06:03 root@directorzone.local */ SHOW INDEX FROM `useravailableas`;
/* 22:06:03 root@directorzone.local */ SELECT COUNT(1) FROM `useravailableas`;
/* 22:06:13 root@directorzone.local */ SET NAMES 'utf8';
/* 22:06:13 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availability';
/* 22:06:13 root@directorzone.local */ SHOW CREATE TABLE `availability`;
/* 22:06:13 root@directorzone.local */ SET NAMES 'latin1';
/* 22:06:13 root@directorzone.local */ SHOW INDEX FROM `availability`;
/* 22:06:13 root@directorzone.local */ SELECT COUNT(1) FROM `availability`;
/* 22:10:36 root@directorzone.local */ SELECT * FROM `availability` LIMIT 0,1000;
/* 22:10:41 root@directorzone.local */ ALTER TABLE `availability` CHANGE `availabilityid` `availabilityid` INT(11)  NOT NULL  AUTO_INCREMENT;
/* 22:10:41 root@directorzone.local */ SET NAMES 'utf8';
/* 22:10:41 root@directorzone.local */ SHOW CREATE TABLE `availability`;
/* 22:10:41 root@directorzone.local */ SET NAMES 'latin1';
/* 22:10:41 root@directorzone.local */ SHOW INDEX FROM `availability`;
/* 22:10:41 root@directorzone.local */ SET NAMES 'utf8';
/* 22:10:41 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availability';
/* 22:10:41 root@directorzone.local */ SET NAMES 'latin1';
/* 22:10:42 root@directorzone.local */ SELECT * FROM `availability` LIMIT 0,1000;
/* 22:10:44 root@directorzone.local */ SHOW COLUMNS FROM `availability`;
/* 22:10:45 root@directorzone.local */ INSERT INTO `availability` (`availabilityid`, `availability`) VALUES (NULL, 'Media comment: I am happy to be contacted for media comment through Directorzone');
/* 22:10:45 root@directorzone.local */ SELECT * FROM `availability` LIMIT 0,1000;
/* 22:10:55 root@directorzone.local */ INSERT INTO `availability` (`availabilityid`, `availability`) VALUES (NULL, 'Speaker roles: I am happy to be contacted for speaker roles through Directorzone');
/* 22:10:55 root@directorzone.local */ SELECT * FROM `availability` LIMIT 0,1000;
/* 22:13:14 root@directorzone.local */ SET NAMES 'utf8';
/* 22:13:14 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 22:13:14 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 22:13:14 root@directorzone.local */ SET NAMES 'latin1';
/* 22:13:14 root@directorzone.local */ SELECT * FROM `user` LIMIT 0,1000;
/* 22:13:17 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 22:14:23 root@directorzone.local */ SET NAMES 'utf8';
/* 22:14:23 root@directorzone.local */ SHOW TABLE STATUS LIKE 'useravailableas';
/* 22:14:23 root@directorzone.local */ SHOW CREATE TABLE `useravailableas`;
/* 22:14:23 root@directorzone.local */ SET NAMES 'latin1';
/* 22:14:23 root@directorzone.local */ SHOW INDEX FROM `useravailableas`;
/* 22:14:23 root@directorzone.local */ SELECT COUNT(1) FROM `useravailableas`;
/* 22:15:52 root@directorzone.local */ RENAME TABLE `useravailableas` TO `availableas`;
/* 22:15:52 root@directorzone.local */ SET NAMES 'utf8';
/* 22:15:52 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availableas';
/* 22:15:52 root@directorzone.local */ SHOW CREATE TABLE `availableas`;
/* 22:15:52 root@directorzone.local */ SET NAMES 'latin1';
/* 22:15:52 root@directorzone.local */ SHOW INDEX FROM `availableas`;
/* 22:15:52 root@directorzone.local */ SELECT COUNT(1) FROM `availableas`;
/* 22:16:00 root@directorzone.local */ ALTER TABLE `availableas` CHANGE `useravailableasid` `availableasid` INT(11)  NOT NULL  AUTO_INCREMENT;
/* 22:16:00 root@directorzone.local */ SET NAMES 'utf8';
/* 22:16:00 root@directorzone.local */ SHOW CREATE TABLE `availableas`;
/* 22:16:00 root@directorzone.local */ SET NAMES 'latin1';
/* 22:16:00 root@directorzone.local */ SHOW INDEX FROM `availableas`;
/* 22:16:00 root@directorzone.local */ SET NAMES 'utf8';
/* 22:16:00 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availableas';
/* 22:16:00 root@directorzone.local */ SET NAMES 'latin1';
/* 22:16:05 root@directorzone.local */ ALTER TABLE `availableas` CHANGE `jobtypeid` `availableas` INT(11)  NULL  DEFAULT NULL;
/* 22:16:05 root@directorzone.local */ SET NAMES 'utf8';
/* 22:16:05 root@directorzone.local */ SHOW CREATE TABLE `availableas`;
/* 22:16:05 root@directorzone.local */ SET NAMES 'latin1';
/* 22:16:05 root@directorzone.local */ SHOW INDEX FROM `availableas`;
/* 22:16:05 root@directorzone.local */ SET NAMES 'utf8';
/* 22:16:05 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availableas';
/* 22:16:05 root@directorzone.local */ SET NAMES 'latin1';
/* 22:16:11 root@directorzone.local */ ALTER TABLE `availableas` DROP `jobtypeother`;
/* 22:16:11 root@directorzone.local */ SET NAMES 'utf8';
/* 22:16:11 root@directorzone.local */ SHOW CREATE TABLE `availableas`;
/* 22:16:11 root@directorzone.local */ SET NAMES 'latin1';
/* 22:16:11 root@directorzone.local */ SET NAMES 'utf8';
/* 22:16:11 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availableas';
/* 22:16:11 root@directorzone.local */ SET NAMES 'latin1';
/* 22:16:11 root@directorzone.local */ SHOW INDEX FROM `availableas`;
/* 22:16:14 root@directorzone.local */ ALTER TABLE `availableas` DROP `userid`;
/* 22:16:14 root@directorzone.local */ SET NAMES 'utf8';
/* 22:16:14 root@directorzone.local */ SHOW CREATE TABLE `availableas`;
/* 22:16:14 root@directorzone.local */ SET NAMES 'latin1';
/* 22:16:14 root@directorzone.local */ SET NAMES 'utf8';
/* 22:16:14 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availableas';
/* 22:16:14 root@directorzone.local */ SET NAMES 'latin1';
/* 22:16:14 root@directorzone.local */ SHOW INDEX FROM `availableas`;
/* 22:16:16 root@directorzone.local */ SELECT * FROM `availableas` LIMIT 0,1000;
/* 22:16:24 root@directorzone.local */ SHOW COLUMNS FROM `availableas`;
/* 22:16:29 root@directorzone.local */ INSERT INTO `availableas` (`availableasid`, `availableas`) VALUES (NULL, 'Spokesperson');
/* 22:16:29 root@directorzone.local */ SELECT * FROM `availableas` LIMIT 0,1000;
/* 22:16:36 root@directorzone.local */ ALTER TABLE `availableas` CHANGE `availableas` `availableas` VARCHAR(100)  NULL  DEFAULT NULL;
/* 22:16:36 root@directorzone.local */ SET NAMES 'utf8';
/* 22:16:36 root@directorzone.local */ SHOW CREATE TABLE `availableas`;
/* 22:16:36 root@directorzone.local */ SET NAMES 'latin1';
/* 22:16:36 root@directorzone.local */ SHOW INDEX FROM `availableas`;
/* 22:16:36 root@directorzone.local */ SET NAMES 'utf8';
/* 22:16:36 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availableas';
/* 22:16:36 root@directorzone.local */ SET NAMES 'latin1';
/* 22:16:37 root@directorzone.local */ SELECT * FROM `availableas` LIMIT 0,1000;
/* 22:16:38 root@directorzone.local */ SHOW COLUMNS FROM `availableas`;
/* 22:16:39 root@directorzone.local */ UPDATE `availableas` SET `availableas` = 'spokesperson' WHERE `availableasid` = '1';
/* 22:16:39 root@directorzone.local */ SELECT * FROM `availableas` LIMIT 0,1000;
/* 22:16:43 root@directorzone.local */ UPDATE `availableas` SET `availableas` = 'Spokesperson' WHERE `availableasid` = '1';
/* 22:16:43 root@directorzone.local */ SELECT * FROM `availableas` LIMIT 0,1000;
/* 22:16:48 root@directorzone.local */ INSERT INTO `availableas` (`availableasid`, `availableas`) VALUES (NULL, 'Speaker');
/* 22:16:48 root@directorzone.local */ SELECT * FROM `availableas` LIMIT 0,1000;
/* 22:16:52 root@directorzone.local */ INSERT INTO `availableas` (`availableasid`, `availableas`) VALUES (NULL, 'Expert Witness');
/* 22:16:52 root@directorzone.local */ SELECT * FROM `availableas` LIMIT 0,1000;
/* 22:17:20 root@directorzone.local */ SET NAMES 'utf8';
/* 22:17:20 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 22:17:20 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 22:17:20 root@directorzone.local */ SET NAMES 'latin1';
/* 22:17:20 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 22:17:20 root@directorzone.local */ SELECT COUNT(1) FROM `user`;
/* 22:17:26 root@directorzone.local */ SELECT * FROM `user` LIMIT 0,1000;
/* 22:17:38 root@directorzone.local */ ALTER TABLE `user` ADD `availableasid` INT  NULL  DEFAULT NULL  AFTER `talentpoolpublishstatusid`;
/* 22:17:38 root@directorzone.local */ SET NAMES 'utf8';
/* 22:17:38 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 22:17:38 root@directorzone.local */ SET NAMES 'latin1';
/* 22:17:38 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 22:17:38 root@directorzone.local */ SET NAMES 'utf8';
/* 22:17:38 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 22:17:38 root@directorzone.local */ SET NAMES 'latin1';
/* 22:19:13 root@directorzone.local */ SET NAMES 'utf8';
/* 22:19:13 root@directorzone.local */ SHOW TABLE STATUS LIKE 'availableas';
/* 22:19:13 root@directorzone.local */ SHOW CREATE TABLE `availableas`;
/* 22:19:13 root@directorzone.local */ SET NAMES 'latin1';
/* 22:19:13 root@directorzone.local */ SHOW INDEX FROM `availableas`;
/* 22:19:13 root@directorzone.local */ SELECT COUNT(1) FROM `availableas`;
/* 22:19:19 root@directorzone.local */ SHOW VARIABLES LIKE 'default_storage_engine';
/* 22:19:26 root@directorzone.local */ SET NAMES 'utf8';
/* 22:19:26 root@directorzone.local */ CREATE TABLE `whoswhodisplay` (id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT);
/* 22:19:26 root@directorzone.local */ SHOW TABLE STATUS LIKE 'whoswhodisplay';
/* 22:19:26 root@directorzone.local */ SHOW CREATE TABLE `whoswhodisplay`;
/* 22:19:26 root@directorzone.local */ SET NAMES 'latin1';
/* 22:19:26 root@directorzone.local */ SHOW INDEX FROM `whoswhodisplay`;
/* 22:19:26 root@directorzone.local */ SELECT COUNT(1) FROM `whoswhodisplay`;
/* 22:19:35 root@directorzone.local */ ALTER TABLE `whoswhodisplay` CHANGE `id` `whoswhodisplayid` INT(11)  UNSIGNED  NOT NULL  AUTO_INCREMENT;
/* 22:19:35 root@directorzone.local */ SET NAMES 'utf8';
/* 22:19:35 root@directorzone.local */ SHOW CREATE TABLE `whoswhodisplay`;
/* 22:19:35 root@directorzone.local */ SET NAMES 'latin1';
/* 22:19:35 root@directorzone.local */ SHOW INDEX FROM `whoswhodisplay`;
/* 22:19:35 root@directorzone.local */ SET NAMES 'utf8';
/* 22:19:35 root@directorzone.local */ SHOW TABLE STATUS LIKE 'whoswhodisplay';
/* 22:19:35 root@directorzone.local */ SET NAMES 'latin1';
/* 22:19:39 root@directorzone.local */ ALTER TABLE `whoswhodisplay` ADD `whoswhodisplay` INT  NULL  DEFAULT NULL  AFTER `whoswhodisplayid`;
/* 22:19:39 root@directorzone.local */ SET NAMES 'utf8';
/* 22:19:39 root@directorzone.local */ SHOW CREATE TABLE `whoswhodisplay`;
/* 22:19:39 root@directorzone.local */ SET NAMES 'latin1';
/* 22:19:39 root@directorzone.local */ SHOW INDEX FROM `whoswhodisplay`;
/* 22:19:39 root@directorzone.local */ SET NAMES 'utf8';
/* 22:19:39 root@directorzone.local */ SHOW TABLE STATUS LIKE 'whoswhodisplay';
/* 22:19:39 root@directorzone.local */ SET NAMES 'latin1';
/* 22:19:46 root@directorzone.local */ ALTER TABLE `whoswhodisplay` CHANGE `whoswhodisplay` `whoswhodisplay` VARCHAR(50)  NULL  DEFAULT NULL;
/* 22:19:46 root@directorzone.local */ SET NAMES 'utf8';
/* 22:19:46 root@directorzone.local */ SHOW CREATE TABLE `whoswhodisplay`;
/* 22:19:46 root@directorzone.local */ SET NAMES 'latin1';
/* 22:19:46 root@directorzone.local */ SHOW INDEX FROM `whoswhodisplay`;
/* 22:19:46 root@directorzone.local */ SET NAMES 'utf8';
/* 22:19:46 root@directorzone.local */ SHOW TABLE STATUS LIKE 'whoswhodisplay';
/* 22:19:46 root@directorzone.local */ SET NAMES 'latin1';
/* 22:19:49 root@directorzone.local */ SELECT * FROM `whoswhodisplay` LIMIT 0,1000;
/* 22:20:02 root@directorzone.local */ INSERT INTO `whoswhodisplay` (`whoswhodisplayid`, `whoswhodisplay`) VALUES (NULL, NULL);
/* 22:20:02 root@directorzone.local */ SELECT * FROM `whoswhodisplay` LIMIT 0,1000;
/* 22:20:08 root@directorzone.local */ INSERT INTO `whoswhodisplay` (`whoswhodisplayid`, `whoswhodisplay`) VALUES (NULL, NULL);
/* 22:20:08 root@directorzone.local */ SELECT * FROM `whoswhodisplay` LIMIT 0,1000;
/* 22:20:09 root@directorzone.local */ SHOW COLUMNS FROM `whoswhodisplay`;
/* 22:20:20 root@directorzone.local */ UPDATE `whoswhodisplay` SET `whoswhodisplay` = 'In Public Profile' WHERE `whoswhodisplayid` = '1';
/* 22:20:20 root@directorzone.local */ SELECT * FROM `whoswhodisplay` LIMIT 0,1000;
/* 22:20:29 root@directorzone.local */ UPDATE `whoswhodisplay` SET `whoswhodisplay` = 'Member View Only' WHERE `whoswhodisplayid` = '2';
/* 22:20:29 root@directorzone.local */ SELECT * FROM `whoswhodisplay` LIMIT 0,1000;
/* 22:20:40 root@directorzone.local */ INSERT INTO `whoswhodisplay` (`whoswhodisplayid`, `whoswhodisplay`) VALUES (NULL, 'Directorzone Administrator View Only');
/* 22:20:40 root@directorzone.local */ SELECT * FROM `whoswhodisplay` LIMIT 0,1000;
/* 22:20:46 root@directorzone.local */ SET NAMES 'utf8';
/* 22:20:46 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 22:20:46 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 22:20:46 root@directorzone.local */ SET NAMES 'latin1';
/* 22:20:46 root@directorzone.local */ SELECT * FROM `user` LIMIT 0,1000;
/* 22:20:50 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 22:20:59 root@directorzone.local */ ALTER TABLE `user` ADD `whoswhodisplayid` INT  NULL  DEFAULT NULL  AFTER `availableasid`;
/* 22:20:59 root@directorzone.local */ SET NAMES 'utf8';
/* 22:20:59 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 22:20:59 root@directorzone.local */ SET NAMES 'latin1';
/* 22:20:59 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 22:20:59 root@directorzone.local */ SET NAMES 'utf8';
/* 22:20:59 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 22:20:59 root@directorzone.local */ SET NAMES 'latin1';
/* 22:24:09 root@directorzone.local */ ALTER TABLE `user` ADD `whoswhosectorid` INT  NULL  DEFAULT NULL  AFTER `whoswhodisplayid`;
/* 22:24:09 root@directorzone.local */ SET NAMES 'utf8';
/* 22:24:09 root@directorzone.local */ SHOW CREATE TABLE `user`;
/* 22:24:09 root@directorzone.local */ SET NAMES 'latin1';
/* 22:24:09 root@directorzone.local */ SHOW INDEX FROM `user`;
/* 22:24:09 root@directorzone.local */ SET NAMES 'utf8';
/* 22:24:09 root@directorzone.local */ SHOW TABLE STATUS LIKE 'user';
/* 22:24:09 root@directorzone.local */ SET NAMES 'latin1';
