
<?php echo $this->partial('company-nav.phtml'); ?>

<?php 

    if (false === $this->hasOwner) {
?>
        <h4>Take ownership of this company</h4>
        <p>
        
<?php 
        if (true == $this->loggedOn) {
?>
            If you would like to take ownership of this company profile, please fill out the box below giving us details of your relationship with the company.
<?php
        } else {
?>
            Please login in order to make a request to take ownership of this company profile.     
<?php
        }            
?>
        </p>
        <p>
            Ownership of a company profile allows you to edit the company profile and also to assign other members as editors.
        </p>
    <?php
        echo $this->BootstrapForm(
            $this->form,
            '',
            $this->url(null, ['id'=>$this->companyId] )
        );
    }
