<script src="/js/jquery-file-upload/js/vendor/jquery.ui.widget.js"></script>
<script src="/js/jquery-file-upload/js/jquery.iframe-transport.js"></script>
<script src="/js/jquery-file-upload/js/jquery.fileupload.js"></script>

<script>

$(document).ready(function() {
	
	$(document).delegate('.linkSearchForCompanyNumber', 'click', function() {
		var name = $(this).attr('company-name');
		
		$('#lightboxSearchForCompany input#searchCompanyName').val(name);

		$('select#searchresults').empty();
		
		$('#lightboxSearchForCompany').modal();

		var url = "/ajax/company/search?name=" + name;
		
		$.ajax({
			url: url
		}).done(function(data) {
			$.each(data.hits.hits, function (key, value) {
				var companyNumber = value['_source']['number'];
				var companyName = value['_source']['name'];
				$('select#searchresults')
				    .append($("<option></option>")
				    .attr("value", companyNumber)
				    .text(companyNumber + " " + companyName)); 
			});
		});
	});
	
	$('#fileupload').fileupload({
		type: 'json',
        done: function (e, data) {

            if (data.result.files[0].error) {
                alert(data.result.files[0].error);
            }

            window.location = '/admin/companies';
            
        },
        fail: function (e, data) {

            alert('There was an unexpected error.  ' +
            	  'The data may have uploaded successfully anyway.  ' +
            	  'Please check the figures on the left after ' +
            	  'closing this box.');

            window.location = '/admin/companies';
            
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress').css(
                    'display',
                    'block'
                );
            $('#progress .bar').css(
                'width',
                progress + '%'
            );
        },
    });

	var page = 1;
	var size = 10;
	var type = "U";

	$(".filter").click(function() {
		$(".filter").removeClass('active');
		$(this).addClass('active');
		page = 1;
		size = 10;
		switch ($(this).attr('id')) {
		  case 'live' : type = 'L'; break;
		  case 'pending' : type = 'P'; break;
		  case 'conflicts' : type = 'C'; break;
		  case 'companies-house' : type = 'H'; break;
		  case 'removed' : type = 'R'; break;
		  case 'unmatched' : type = 'U'; break;
		}

		loadTable(type, page, size);
	});

	$("li#next").click(function() {
		page ++;
		loadTable(type, page, size);
	});

	$("li#previous").click(function() {
		if (!$(this).hasClass('disabled')) {
    		page --;
    		loadTable(type, page, size);
		}
	});

	loadTable(type, page, size);
});

function loadTable(type, page, size)
{
	$('table#companies').find("tr:gt(0)").remove();

	$('table#companies tr:last').after(
		'<tr>' +
		'<td style="text-align:center" colspan="4"><img src="/img/ajax/ajax-loader.gif"></td>' +
		'</tr>'
    );
	
	var url = "/ajax/company/list?type=" + type + "&page=" + page + "&size=" + size;

	$.ajax({
		url: url
	}).done(function(data) {

		$('table#companies').find("tr:gt(0)").remove();
		
		$('li#next').removeClass('disabled');
		$('li#previous').removeClass('disabled');
		
		if (data.total <= page * size) {
			$('li#next').addClass('disabled');
		}

		if (page == 1) {
			$('li#previous').addClass('disabled');
		}
		
		$.each(data.results, function(key, value) {
			if (type == 'U') {
				value.number = '<a class="linkSearchForCompanyNumber" company-name="' + value.name + '" href="#">Search</a>'
			}
    		$('table#companies tr:last').after(
    			'<tr>' +
    			'<td>' + value.number + '</td>' +
    			'<td>' + value.name + '</td>' +
    			'</tr>'
    	    );
    	});
	});
}

</script>