# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "raring64"

    config.vm.network :forwarded_port, guest: 80, host: 8081
    config.vm.network :forwarded_port, guest: 9200, host: 9201
    config.vm.network :forwarded_port, guest: 3306, host: 33060

   config.vm.provider "vmware_fusion" do |v, override|
         v.vmx["memsize"] = "2048"
         v.vmx["numvcpus"] = "1"
  	override.vm.box_url = "https://s3.amazonaws.com/life360-vagrant/raring64.box"
   end

   config.vm.provider "vmware_workstation" do |v, override|
         v.vmx["memsize"] = "2048"
         v.vmx["numvcpus"] = "1"
  	override.vm.box_url = "https://s3.amazonaws.com/life360-vagrant/raring64.box"
   end

    config.vm.synced_folder "../../../", "/var/www/", :mount_options => ["gid=www-data", "uid=www-data", "dmode=777", "fmode=777"], type: "nfs"

    config.vm.provision "shell", path: "provision.sh"

   #config.vm.provider :virtualbox do |vb|
  	#vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", 8, "--cpuexecutioncap", 95, "--hwvirtex", "on"]
   #end

end
