<h3><?php echo $this->name; ?></h3>
<h5>
	<a href="/directories/company/<?php echo $this->companydirectoryid; ?>/overview">Edit this company</a> | <a id="deletecompany"
		href="/directories/company/<?php echo $this->companydirectoryid; ?>/delete">Delete this company</a> | <a
		href="/directories/company/<?php echo $this->companydirectoryid; ?>/owners">This is my company</a>
</h5>

<div class="row">
	<div class="col-md-12">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#" id="tab-overview">Overview</a></li>
			<li><a href="#" id="tab-officers">Officers</a></li>
			<li><a href="#" id="tab-metrics">Metrics</a></li>
			<li><a href="#" id="tab-relationships">Relationships</a></li>
			<li><a href="#" id="tab-markets">Markets</a></li>
			<li><a href="#" id="tab-newsfeeds">News Feeds</a></li>

		</ul>
	</div>
</div>
<div class="tab-content" id="tab-content">
    <div class="tab-partial" id="overview">
        <?php echo $this->partial('company-details/overview.phtml'); ?>
    </div>
    <div class="tab-partial" id="officers" style="display:none">
        <?php echo $this->partial('company-details/officers.phtml'); ?>
    </div>
    <div class="tab-partial" id="metrics" style="display:none">
    </div>
    <div class="tab-partial" id="relationships" style="display:none">
    </div>
    <div class="tab-partial" id="markets" style="display:none">
    </div>
    <div class="tab-partial" id="newsfeeds" style="display:none">
    </div>
    
</div>

<script>
$(document).ready(function() {
    $('#deletecompany').click(function() {
        return confirm('Do you want to delete this company?');
    });

    function switchActiveTab(activeTab) {
		$('ul.nav-tabs li').each(function () {
			$(this).removeClass('active');
		});
		$('div.tab-partial').each(function () {
			if ($(this).css('display') == 'block') {
			    $(this).fadeOut(250, function() {
			    	$(activeTab).parent().addClass('active');
			        var contentDivId = activeTab.attr('id').replace('tab-', '');
			        var newTab = $('div#' + contentDivId);
			        newTab.fadeIn();
			    });
			}
		});
		
    }
    
    $(document).delegate('a[id^=tab-]', 'click', function() {
        switchActiveTab($(this));
	});
});
</script>


