<h3><?php echo $this->forename . ' ' . $this->surname; ?></h3>
<h5><a href="/directories/people/<?php echo $this->whoswhoid; ?>/overview">Edit this person</a></h5>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Address</h3>
            </div>
            <div class="panel-body">
            <?php
            $this->Address($this->address);
            ?>
            </div>
        </div>
        
                <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Companies</h3>
            </div>
            <div class="panel-body">
            <?php foreach ($this->companies as $company): ?>
            <a href="<?php echo $this->url('directories/company-directory/company-details', ['id' => $company['companydirectoryid']]); ?>"><?php echo $company['name']; ?></a>
            <br>
            <?php endforeach; ?>
            
            </div>
        </div>
        
       
        
    </div>
    <div class="col-md-8">
    <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Who's Who Description</h3>
            </div>
            <div class="panel-body">
            <?php 
                echo $this->profile;
            ?>
            </div>
        </div>
 
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading">
                      <h3 class="panel-title">News Feed</h3>
                    </div>
                    <div class="panel-body">
                    <table class="table">
                    <?php
                        foreach ($this->bing as $bingResult) {
                    ?>
                        <tr>
                            <td>
                                <h5><a href="<?php echo $bingResult['Url']; ?>"><?php echo $bingResult['Title']; ?></a></h5>
                                <?php echo $bingResult['Description']; ?>
                            </td>
                        </tr>

                    <?php
                        }
                    ?>
                    </table>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">

                
                <div class="panel panel-info">
                    <div class="panel-heading">
                      <h3 class="panel-title">Twitter Feed</h3>
                    </div>
                    <div class="panel-body">
                    <table class="table">
                    <?php
                        foreach ($this->tweets as $tweet) {
                    ?>
                        <tr>
                            <td>
                                <img src="<?php echo $tweet['userimage']; ?>">
                            </td>
                            <td>
                                <?php echo $tweet['text']; ?>
                            </td>
                        </tr>

                    <?php
                        }
                    ?>
                    </table>
                    </div>
                </div>

                </div>
            </div>
        </div>
    </div> 
</div>

