
<table id="owners" class="table table-striped table-bordered table-hover">
<tr>
<th><a class="columnHeading" data-column-number="1">Company</a></th>
<th><a class="columnHeading" data-column-number="2">Owner</a></th>
<th><a class="columnHeading" data-column-number="3">Request Date</a></th>
<th><a class="columnHeading" data-column-number="4">Text</a></th>
<th><a class="columnHeading" data-column-number="5">Status</a></th>
</tr>
</table>

<ul class="pager">
<li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
<li class="next" id="next"><a href="#">Next &rarr;</a></li>
</ul>

