
<div class="modal fade" id="sendMessageDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Message</h4>
      </div>
      <div class="modal-body">
        <textarea id="messagecontent" style="width:100%;height:10em">
        </textarea>
      </div>
      <div class="modal-footer">
        <button id="cancelmessage" type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button id="sendmessage" type="button" class="btn btn-primary" data-dismiss="modal">Send Message</button>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function () {
	var receiverId = -1;
	
	$('a#sendmessagedialog').click(function () {
		receiverId = $(this).attr('data-id');
		$('div#sendMessageDialog').modal({
			  keyboard: false
		});
	});

	$('button#cancelmessage').click(function () {
		receiverId = -1;
	});
	
	$('button#sendmessage').click(function () {

	});
	
	$('div#sendMessageDialog').on('hidden.bs.modal', function (e) {
		if (receiverId != -1) {
			  alert('Message sent to ' + receiverId);
		}
	})
});
</script>