
<div class="modal fade" id="sendMessageDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Message</h4>
      </div>
      <div class="modal-body">
        Title
        <input id="messagetitle" style="width:100%;">
        Message
        <textarea id="messagecontent" style="width:100%;height:10em">
        </textarea>
      </div>
      <div class="modal-footer">
        <button id="cancelmessage" type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button id="sendmessage" type="button" class="btn btn-primary" data-dismiss="modal">Send Message</button>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function () {
	var receiverId = -1;
	
	$('a#sendmessagedialog').click(function () {
		receiverId = $(this).attr('data-id');
		$('div#sendMessageDialog').modal({
			  keyboard: false
		});
	});

	$('button#cancelmessage').click(function () {
		receiverId = -1;
	});
	
	$('button#sendmessage').click(function () {

	});
	
	$('div#sendMessageDialog').on('hidden.bs.modal', function (e) {
		if (receiverId != -1) {
			var url = '/ajax/send-message/' + receiverId + '/1';
			var title = $('input#messagetitle').val();
			var content = $('textarea#messagecontent').val();
			$.ajax({
				'url' : url,
				'type' : 'POST',
				'data' : {title: title, content: content},
			}).done(function(msg) {
				if (msg.success) {
				    alert('Message sent successfully');
				} else {
					alert('There was an unknown error sending your message');
				}
			});
		}
	})
});
</script>