
<div class="modal fade" id="sendMessageDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Message</h4>
      </div>
      <div class="modal-body">
        <?php if (!empty($this->messageRecipient)): ?>
        To
        <input id="messagerecipient" style="width:100%;" value="<?= $this->messageRecipient ?>">
        <?php endif; ?>
        Title
        <input id="messagetitle" style="width:100%;" value="<?= $this->messageTitle ?>">
        Message
        <textarea id="messagecontent" style="width:100%;height:10em">
        </textarea>
      </div>
      <div class="modal-footer">
        <button id="cancelmessage" type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button id="sendmessage" type="button" class="btn btn-primary" data-dismiss="modal">Send Message</button>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function () {
	var receiverId = -1;
	var receiverName = '';
	
	$('a#sendmessagedialog').click(function () {
		receiverId = $(this).attr('data-id');
		receiverName = $(this).attr('data-name');
		$('#messagerecipient').val(receiverName);
		$('div#sendMessageDialog').modal({
			  keyboard: false
		});
	});

	$('a#forwardmessagedialog').click(function () {
		receiverId = -1;
		$('#messagerecipient').val('');
		$('div#sendMessageDialog').modal({
			  keyboard: false
		});
	});

	$('a#deletemessage').click(function () {
		if (confirm('Are you sure you want to delete this message?')) {
			var messageId = $(this).attr('data-messageid');
			var url = '/ajax/delete-message/' + messageId;
			$.ajax({
				'url' : url,
			}).done(function(msg) {
				if (msg.success) {
					window.location = '/myaccount/inbox';
				} else {
					if (msg.message) {
						alert(msg.message);
					} else {
						alert('There was an unknown error deleting your message');
					}
				}
			});
		}
	});

	$('a#archivemessage').click(function () {
		if (confirm('Are you sure you want to archive this message?')) {
			var messageId = $(this).attr('data-messageid');
			var url = '/ajax/archive-message/' + messageId;
			$.ajax({
				'url' : url,
			}).done(function(msg) {
				if (msg.success) {
					window.location = '/myaccount/inbox';
				} else {
					if (msg.message) {
						alert(msg.message);
					} else {
						alert('There was an unknown error archiving your message');
					}
				}
			});
		}
	});

	$('a#unarchivemessage').click(function () {
		if (confirm('Are you sure you want to unarchive this message?')) {
			var messageId = $(this).attr('data-messageid');
			var url = '/ajax/unarchive-message/' + messageId;
			$.ajax({
				'url' : url,
			}).done(function(msg) {
				if (msg.success) {
					window.location = '/myaccount/inbox';
				} else {
					if (msg.message) {
						alert(msg.message);
					} else {
						alert('There was an unknown error unarchiving your message');
					}
				}
			});
		}
	});

	$('a#flagmessage').click(function () {
		var messageId = $(this).attr('data-messageid');
		var url = '/ajax/flag-message/' + messageId;
		$.ajax({
			'url' : url,
		}).done(function(msg) {
			if (msg.success) {
				window.location.reload();
			} else {
				if (msg.message) {
					alert(msg.message);
				} else {
					alert('There was an unknown error flagging your message');
				}
			}
		});
	});

	$('a#unflagmessage').click(function () {
		var messageId = $(this).attr('data-messageid');
		var url = '/ajax/unflag-message/' + messageId;
		$.ajax({
			'url' : url,
		}).done(function(msg) {
			if (msg.success) {
				window.location.reload();
			} else {
				if (msg.message) {
					alert(msg.message);
				} else {
					alert('There was an unknown error unflagging your message');
				}
			}
		});
	});
	
	$('button#cancelmessage').click(function () {
		receiverId = -1;
	});
	
	$('button#sendmessage').click(function () {

	});

	$('div#sendMessageDialog').on('hidden.bs.modal', function (e) {
		var receiverName = $('#messagerecipient').val();
		if (receiverId != -1) {
			var url = '/ajax/send-message/' + receiverId + '/1';
			var title = $('input#messagetitle').val();
			var content = $('textarea#messagecontent').val();
			$.ajax({
				'url' : url,
				'type' : 'POST',
				'data' : {receiverName: receiverName, title: title, content: content},
			}).done(function(msg) {
				if (msg.success) {
					if (msg.message) {
						alert(msg.message);
					}
				} else {
					if (msg.message) {
						alert(msg.message);
					} else {
						alert('There was an unknown error sending your message');
					}
				}
			});
		}
	})
});
</script>