<h3><?php echo $this->name; ?></h3>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Address</h3>
            </div>
            <div class="panel-body">
            <?php 
                echo $this->addressline1 . '<br>';
                echo trim($this->addressline2) == '' ? '' : ($this->addressline2 . '<br>');
                echo trim($this->addressline3) == '' ? '' : ($this->addressline3 . '<br>');
                echo trim($this->addressline4) == '' ? '' : ($this->addressline4 . '<br>');
                echo trim($this->addressline5) == '' ? '' : ($this->addressline5 . '<br>');
                echo trim($this->town) == '' ? '' : ($this->town . '<br>');
                echo trim($this->county) == '' ? '' : ($this->county . '<br>');
                echo trim($this->country) == '' ? '' : ($this->country . '<br>');
                echo $this->postcode;
            ?>
            </div>
        </div>
        
        <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Officers</h3>
            </div>
            <div class="panel-body">
            <table class="table"></table>
            </div>
        </div>
        
    </div>
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Sectors</h3>
            </div>
            <div class="panel-body">
            <?php 
                echo trim($this->siccode1) == '' ? '' : ($this->siccode1 . '<br>');
                echo trim($this->siccode2) == '' ? '' : ($this->siccode2 . '<br>');
                echo trim($this->siccode3) == '' ? '' : ($this->siccode3 . '<br>');
                echo trim($this->siccode4) == '' ? '' : ($this->siccode4 . '<br>');
            ?>
            </div>
        </div>
   
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading">
                      <h3 class="panel-title">Key Data</h3>
                    </div>
                    <div class="panel-body">
                    <table class="table">
                    <tr><td>Category</td><td><?php echo $this->category; ?></td></tr>
                    <tr><td>Incorporated</td><td><?php echo $this->incorporationdate; ?></td></tr>
                    <tr><td>Status</td><td><?php echo $this->detailstatus; ?></td></tr>
                    </table>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading">
                      <h3 class="panel-title">News Feed</h3>
                    </div>
                    <div class="panel-body">
                    <table class="table"></table>
                    </div>
                </div>
                
                <div class="panel panel-info">
                    <div class="panel-heading">
                      <h3 class="panel-title">Twitter Feed</h3>
                    </div>
                    <div class="panel-body">
                    <table class="table"></table>
                    </div>
                </div>
            </div>
        </div>
    </div> 
</div>

