<?php echo $this->partial('directory-nav.phtml'); ?>
<h3>Company directory</h3>
<h5><a href="/directories/company/new">Add new company</a></h5>

<table id="companies" data-link="row" class="rowlink table table-striped table-bordered table-hover">
<caption>Sort by <a class="columnHeading fixed-order" data-column-number="-1">newest</a> | <a class="columnHeading fixed-order" data-column-number="1">oldest</a></caption>        
<tr>
<th><a class="columnHeading" data-column-number="1">Number</a></th>
<th><a class="columnHeading" data-column-number="2">Name</a></th>
<th><a class="columnHeading" data-column-number="3">CEO</a></th>
<th><a class="columnHeading" data-column-number="4">Sectors</a></th>
<th><a class="columnHeading" data-column-number="5">Turnover</a></th>
<th><a class="columnHeading" data-column-number="6">Added</a></th>
</tr>
</table>

<ul class="pager">
<li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
<li class="next" id="next"><a href="#">Next &rarr;</a></li>
</ul>

<script>

$(document).ready(function() {
	$(document).delegate('.columnHeading', 'click', function() {
		loadTheTable();
	});
    loadTheTable();
});

function loadTheTable()
{
	netsensia_Pager(
			1,
			10,
			'companies',
			'/ajax/company/list',
			function(key, value) {
				var url = '/directories/company/' + value.internalId;
				
				var newRow = '<tr>';
				newRow += '<td><a href="' + url + '">' + value.number + '</a></td>';
				newRow += '<td>' + value.name + '</td>';
				newRow += '<td>' + value.ceo + '</td>';
				newRow += '<td>' + value.sectors + '</td>';
				newRow += '<td>' + value.turnover + '</td>';
				newRow += '<td class="prettydate">' + prettyDate(value.createdTime) + '</td>';
				newRow += '</tr>';
		
				return newRow;
			}
		);

	
}

</script>
