<?php echo $this->partial('directory-nav.phtml'); ?>
<h3>People directory</h3>

<table id="people" data-link="row" class="rowlink table table-striped table-bordered table-hover">
<tr>
<th><a class="columnHeading" data-column-number="2">Name</a></th>
<th><a class="columnHeading" data-column-number="3">Companies</a></th>
<th><a class="columnHeading" data-column-number="1">Added</a></th>
</tr>
</table>

<ul class="pager">
<li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
<li class="next" id="next"><a href="#">Next &rarr;</a></li>
</ul>

<script>

$(document).ready(function() {
	$(document).delegate('.columnHeading', 'click', function() {
		loadTheTable();
	});
	loadTheTable();
});

function loadTheTable()
{
	var startPage = <?php echo $this->startPage; ?>;
	netsensia_Pager(
			startPage,
			20,
			'people',
			'/ajax/whoswho/list',
			function(key, value) {
				var url = '/directories/people/' + value.internalId;
				var newRow = '<tr>';
				newRow += '<td><a href="' + url + '">' + value.name + '</a></td>';
				newRow += '<td>' + value.numappointments + '</td>';
				newRow += '<td class="prettydate">' + prettyDate(value.createdTime) + '</td>';
				newRow += '</tr>';

				return newRow;
			}
		);	
}

</script>