<?php echo $this->partial('directory-nav.phtml'); ?>
<h3>People directory</h3>

<table id="people" data-link="row" class="table table-striped table-bordered table-hover">
<tr><th>Name</th><th>Company</th><th>Appointment Type</th><th>Date of Birth</th></tr>
</table>

<ul class="pager">
<li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
<li class="next" id="next"><a href="#">Next &rarr;</a></li>
</ul>

<script>

$(document).ready(function() {

	netsensia_Pager(
		1,
		20,
		'people',
		'/ajax/people/list',
		function(key, value) {
			var url = '/directories/people/' + value.internalId;
			var newRow = '<tr>';
			newRow += '<td><a href="' + url + '">' + value.name + '</a></td>';
			newRow += '<td>' + value.companyname + '</td>';
			newRow += '<td>' + value.appointmenttype + '</td>';
			newRow += '<td>' + value.dob + '</td>';
			newRow += '</tr>';
	
			return newRow;
		}
	);	
});

</script>