# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"

  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
 
    config.vm.network :forwarded_port, guest: 80, host: 8081
    config.vm.network :forwarded_port, guest: 9200, host: 9201
    config.vm.network :forwarded_port, guest: 3306, host: 33060

   config.vm.provider "vmware_fusion" do |v|
         v.vmx["memsize"] = "4096"
         v.vmx["numvcpus"] = "2"
   end

    config.vm.synced_folder "../../", "/var/www/", :mount_options => ["gid=www-data", "uid=www-data", "dmode=777", "fmode=777"]
   config.vm.synced_folder "~/.ssh", "/home/vagrant/keys", :mount_options => []

    config.vm.provision "shell", path: "provision.sh"


   config.vm.provider :virtualbox do |vb|
  vb.customize ["modifyvm", :id, "--memory", "4096", "--cpus", 8, "--cpuexecutioncap", 95, "--hwvirtex", "on"]
   end

end
