# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1399839341);
user_pref("app.update.lastUpdateTime.background-update-timer", 1399839216);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1399838964);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1399839089);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.migration.version", 15);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 6);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140314220517");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 871);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20140314220517");
user_pref("browser.startup.homepage_override.mstone", "28.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1399925236196");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1399838836196");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.firstPaint", 877);
user_pref("datareporting.sessions.current.main", 20);
user_pref("datareporting.sessions.current.sessionRestored", 911);
user_pref("datareporting.sessions.current.startTime", "1399838836024");
user_pref("datareporting.sessions.current.totalTime", 16);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"firefox-hotfix@mozilla.org\":{\"version\":\"20140319.01\",\"type\":\"extension\",\"descriptor\":\"/Users/chris/git/directorzone/tests/selenium/firefoxProfile/extensions/firefox-hotfix@mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:28.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140319.01");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"web2pdfextension@web2pdf.adobedotcom\":{\"descriptor\":\"/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/web2pdfextension@web2pdf.adobedotcom\",\"mtime\":1389906387000,\"rdfTime\":1348459481000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/Firefox.app/Contents/MacOS/./browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1396607339000,\"rdfTime\":1396607339000}}}]");
user_pref("extensions.lastAppVersion", "28.0");
user_pref("extensions.lastPlatformVersion", "28.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140314220517");
user_pref("gecko.mstone", "28.0");
user_pref("idle.lastDailyNotification", 1399839299);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1399839299);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1399839299);
user_pref("toolkit.telemetry.previousBuildID", "20140314220517");
user_pref("urlclassifier.download_allow_table", "");
user_pref("urlclassifier.download_block_table", "");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1402430841);
