<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Netsensia\Module'                        => __DIR__ . '/Module.php',
    'Netsensia\Controller\IndexController' => __DIR__ . '/src/Netsensia/Controller/IndexController.php',
    'NetsensiaTest\Framework\TestCase'        => __DIR__ . '/tests/Netsensia/Framework/TestCase.php',
    'NetsensiaTest\SampleTest'                => __DIR__ . '/tests/Netsensia/SampleTest.php',
);
