<ul class="nav nav-pills">
<?php 

$routes = [
   'account-personal' => 'Personal',
   'account-profile' => 'Talent Pool',
   'account-directory' => "Who's Who",
   'account-contact' => 'Contact',
   'account-membership' => 'Membership',
   'account-account' => 'Account',
   'account-publish' => 'Publish',
   'account-myarticles' => 'My Articles',
   'account-inbox' => 'Inbox',
   'account-preferences' => 'Preferences',
   'account-experience' => 'Experience',
   'account-company' => 'Company', 
];

foreach ($routes as $route => $text) {
?>
    <li class="<?php echo ($this->url() == $this->url($route) ? 'active' : ''); ?>">
        <a href="<?php echo $this->url($route); ?>">
            <?php echo $text; ?>
        </a>
    </li>
<?php
}

?>
</ul>