<ul class="nav nav-pills">
<?php 

$routes = [
   'admin-companies' => 'Companies',
   'admin-people' => 'People',
   'admin-users' => 'Users',
   'admin-publishing' => 'Publishing',
   'admin-data' => 'Data',
   'admin-membership' => 'Membership',
   'admin-advertising' => 'Advertising',
   'admin-pages' => 'Pages',
];

foreach ($routes as $route => $text) {
?>
    <li class="<?php echo ($this->url() == $this->url($route) ? 'active' : ''); ?>">
        <a href="<?php echo $this->url($route); ?>">
            <?php echo $text; ?>
        </a>
    </li>
<?php
}

?>
</ul>