<ul class="nav nav-pills">
<?php 

$routes = [
   'admin-companies' => 'Companies',
   'admin-members' => 'Members',
   'admin-company-owners' => 'Company Owners',
   'admin-this-is-me-claims' => 'Who\'s Who Claims',
];

foreach ($routes as $route => $text) {
?>
    <li class="<?php echo ($this->url() == $this->url($route) ? 'active' : ''); ?>">
        <a href="<?php echo $this->url($route); ?>">
            <?php echo $text; ?>
        </a>
    </li>
<?php
}

?>
</ul>