
<div class="row">

<div class="col-md-4">

<ul class="nav nav-pills nav-stacked" style="max-width:250px;">
<?php 

foreach ($this->filters as $slug => $details) {
?>
    <li id="<?php echo $slug; ?>" class="filter <?php echo ($slug == 'live' ? 'active' : '') ?>">
        <a href="#">
            <?php echo $details['name'] . ' <span class="badge pull-right">' . $details['count'] . '</span>'; ?>
        </a>
    </li>
<?php
}

?>
</ul>
</div>
<div class="col-md-8">

<div class="fileinput fileinput-new" data-provides="fileinput">
  <div class="input-group">
    <div class="form-control uneditable-input span3" data-trigger="fileinput"><i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span></div>
    <span class="input-group-addon btn btn-default btn-file"><span class="fileinput-new">Select file</span>
    <span class="fileinput-exists">Change</span>
    <input id="fileupload" type="file" name="files[]" data-url="/admin/upload/companies" multiple>
    </span>
    <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
  </div>
</div>

<div id="progress" style="display:none">
    <div class="bar" style="height:18px;background-color:#428bca">
    </div>
</div>
        
<table id="companies" class="table">
<tr><th>Number</th><th>Name</th><th>CEO</th><th>Sector</th></tr>
</table>

<ul class="pager">
  <li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
  <li class="next" id="next"><a href="#">Next &rarr;</a></li>
</ul>

</div>

<script src="/js/jquery-file-upload/js/vendor/jquery.ui.widget.js"></script>
<script src="/js/jquery-file-upload/js/jquery.iframe-transport.js"></script>
<script src="/js/jquery-file-upload/js/jquery.fileupload.js"></script>
                                  
<script>


$(document).ready(function() {

	$('#fileupload').fileupload({
        dataType: 'json',
        done: function (e, data) {
            $('#progress').css(
                    'display',
                    'none'
            );
            $.each(data.result.files, function (index, file) {
                if (file.error) {
             	   alert('ERROR: ' + file.error);
                }
            });
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress').css(
                    'display',
                    'block'
                );
            $('#progress .bar').css(
                'width',
                progress + '%'
            );
        },
    });

	var page = 1;
	var size = 10;
	
	$(".filter").click(function() {
		$(".filter").removeClass('active');
		$(this).addClass('active');
	});

	$("li#next").click(function() {
		page ++;
		loadTable(page, size);
	});

	$("li#previous").click(function() {
		if (!$(this).hasClass('disabled')) {
    		page --;
    		loadTable(page, size);
		}
	});

	loadTable(page, size);
});

function loadTable(page, size)
{
	$.ajax({
		url: "/ajax/company/search?page=" + page + "&size=" + size
	}).done(function(data) {

		$('table#companies').find("tr:gt(0)").remove();
		
		$('li#next').removeClass('disabled');
		$('li#previous').removeClass('disabled');
		
		if (data.total <= page * size) {
			$('li#next').addClass('disabled');
		}

		if (page == 1) {
			$('li#previous').addClass('disabled');
		}
		
		$.each(data.results, function(key, value) {
    		$('table#companies tr:last').after(
    			'<tr>' +
    			'<td>' + value.number + '</td>' +
    			'<td>' + value.name + '</td>' +
    			'<td>' + value.ceo + '</td>' +
    			'<td>' + value.sector + '</td>' +
    			'</tr>'
    	    );
    	});
	});
}
</script>