<div class="row">
<div class="col-md-4">
<ul class="nav nav-pills nav-stacked" style="max-width:250px;">
<?php 

foreach ($this->filters as $slug => $details) {
?>
    <li id="<?php echo $slug; ?>" class="filter <?php echo ($slug == 'live' ? 'active' : '') ?>">
        <a href="#">
            <?php echo $details['name'] . ' <span class="badge pull-right">' . $details['count'] . '</span>'; ?>
        </a>
    </li>
<?php
}

?>
</ul>
</div>
<div class="col-md-8">

<table id="companies" class="table">
<tr><th>Number</th><th>Name</th><th>CEO</th><th>Sector</th></tr>
</table>

<ul class="pager">
  <li id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
  <li id="next"><a href="#">Next &rarr;</a></li>
</ul>

</div>

<script>
$(document).ready(function() {
	var page = 1;
	var size = 5;
	
	$(".filter").click(function() {
		$(".filter").removeClass('active');
		$(this).addClass('active');
	});

	$("li#next").click(function() {
		page ++;
		loadTable(page, size);
	});

	$("li#previous").click(function() {
		page --;
		loadTable(page, size);
	});

	loadTable(page, size);
});

function loadTable(page, size)
{
	$.ajax({
		url: "/ajax/company/search?page=" + page + "&size=" + size
	}).done(function(data) {

		$('table#companies').find("tr:gt(0)").remove();
		
		$('li#next').removeClass('disabled');
		$('li#previous').removeClass('disabled');
		
		if (data.total <= page * size) {
			$('li#next').addClass('disabled');
		}

		if (page == 1) {
			$('li#previous').addClass('disabled');
		}
		
		$.each(data.results, function(key, value) {
    		$('table#companies tr:last').after(
    			'<tr>' +
    			'<td>' + value.number + '</td>' +
    			'<td>' + value.name + '</td>' +
    			'<td>' + value.ceo + '</td>' +
    			'<td>' + value.sector + '</td>' +
    			'</tr>'
    	    );
    	});
	});
}
</script>