<ul class="nav nav-pills">
  <li class="active"><a href="<?php echo $this->url('account-profile') ?>">Profile</a></li>
  <li><a href="<?php echo $this->url('account-contact') ?>">Contact</a></li>
  <li><a href="<?php echo $this->url('account-membership') ?>">Membership</a></li>
  <li><a href="<?php echo $this->url('account-account') ?>">Account</a></li>
  <li><a href="<?php echo $this->url('account-publish') ?>">Publishing</a></li>
  <li><a href="<?php echo $this->url('account-inbox') ?>">Inbox</a></li>
  <li><a href="<?php echo $this->url('account-preferences') ?>">Preferences</a></li>
  <li><a href="<?php echo $this->url('account-experience') ?>">Experience</a></li>
  <li><a href="<?php echo $this->url('account-company') ?>">Company</a></li>  
</ul>