<ul class="nav nav-pills">
<?php 

$routes = [
   'directories/company-directory' => 'Companies',
   'directories/people-directory' => "Who's Who",
];

foreach ($routes as $route => $text) {
?>
    <li class="<?php echo ($this->url() == $this->url($route) ? 'active' : ''); ?>">
        <a href="<?php echo $this->url($route); ?>">
            <?php echo $text; ?>
        </a>
    </li>
<?php
}

?>
</ul>