<div class="well well-sm">
<div style="margin-bottom:0.5em">
<strong>Filters:</strong> You may narrow these results by adding tag filters based on sector, geography, key events or functional area
</div>
<select id="filtertype">
<option value="sector">Sector</option>
<option value="geography">Geography</option>
<option value="keyevent">Key Event</option>
<option value="jobarea">Functional Area</option>
</select>
<input type="text" id="searchfilter" placeholder="Start typing..." style="width:20em">
<input type="button" class="button" value="Add filter">
</div>
<input type="hidden" id="filters" value='[{}]'>

<script>
$(document).ready(function() {
	function updateTags()
	{
	}
	
    $('#searchfilter').autocomplete({
        source: function(request, response) {

    		var type = $('#filtertype').val();
    		var url = '/ajax/filter/search/' + type + '/' + request.term;
    		
            $.ajax({
                url: url,
                success: function(data) {
                    alert(data);
                    response(data);
                }
            });
        },
        select: function(event, ui) {
        	$('#searchfilter').val(ui.item.label);
        	var json = $('#filters').val();
        	var currentFilters = jQuery.parseJSON(json);
        	currentFilters.push(ui.item);
        	$('#filters').val(JSON.stringify(currentFilters));
        	updateTags();
        	event.preventDefault();
        }
    });
});
</script>