<ul class="nav nav-pills">
<?php 

$routes = [
    'directories/people-directory/people-details/people-overview' => 'Overview',
    'directories/people-directory/people-details/people-feeds' => 'Feeds',
];

foreach ($routes as $route => $text) {
?>
    <li class="<?php echo (substr($this->url(), 0, strlen($this->url($route))) == $this->url($route) ? 'active' : ''); ?>">
        <a href="<?php echo $this->url($route, ['id'=>$this->whosWhoDetails['whoswhoid']]); ?>">
            <?php echo $text; ?>
        </a>
    </li>
<?php
}

?>
</ul>

<h3><?php echo $this->whosWhoDetails['forename'] . ' ' . $this->whosWhoDetails['surname']; ?></h3>
<h5><a href="/directories/people/<?php echo $this->whosWhoDetails['whoswhoid']; ?>">View person profile page</a></h5>
