<div class="modal fade" id="lightboxSearchForCompany" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Assign company number to uploaded company</h4>
      </div>
      <div class="modal-body">
      Searching for: <input class="form-control" id="searchCompanyName">
      <div id="searchresultscontainer">
      <select class="form-control" id="searchresults">
      </select>
      </div>
      </div>
      <div class="modal-footer">
        <button id="action-cancel" type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button id="action-move-to-pending" type="button" class="btn btn-success">Move to Pending</button>
        <button id="action-move-to-problems" type="button" class="btn btn-warning">Move to Problems</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->