<div class="modal fade" id="lightboxSearchForCompany" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Assign company number to uploaded company</h4>
      </div>
      <div class="modal-body">
      
      <div class="row">
      <div class="col-lg-3">
      <input class="form-control" id="searchCompanyNumber">
      </div>
      <div class="col-lg-9">
      <input class="form-control" id="searchCompanyName">
      </div>
      </div>
      
      <input type="hidden" id="searchCompanyUploadId">
      
      <div id="searchresultscontainer" style="margin-top:5px" class="dropdown">
          <button class="btn dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
            Select company...
            <span class="caret"></span>
          </button>
          <ul id="searchresults" class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        </ul>
      </div>

      </div>
      <div class="modal-footer">
        <button id="action-cancel" type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        
        <button id="action-search-again" type="button" class="btn btn-info has-spinner">
            <span class="spinner"><i class="glyphicon spin glyphicon-refresh"></i></span>
            Search Again
        </button>
        
        <button id="action-move-to-pending" type="button" class="btn btn-success">Move to Pending</button>
        <button id="action-move-to-problems" type="button" class="btn btn-warning">Move to Problems</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->