<div class="modal fade" id="lightboxSearchForOfficers" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Find officers for known company</h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button id="action-cancel" type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        
        <button id="action-confirm-officers" type="button" class="btn btn-success">Confirm</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->