
<div class="fileinput fileinput-new" data-provides="fileinput">
<div class="input-group">
<div class="form-control uneditable-input span3" data-trigger="fileinput">
<i class="glyphicon glyphicon-file fileinput-exists"></i>
<span class="fileinput-filename"></span>
</div>
<span class="input-group-addon btn btn-default btn-file">
<span class="fileinput-new">Select file</span>
<span class="fileinput-exists">Change</span>
<input id="fileupload" type="file" name="files[]" data-url="/admin/upload/companies" multiple>
</span>
<a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
</div>
</div>

<div id="progress" style="display:none">
<div class="bar" style="height:18px;background-color:#428bca">
</div>
</div>

<input id="addsinglecompany" style="width:50%" type="text">&nbsp;<button id="addsinglecompany">Add Single Company to CH List</button>
<input id="addnonchcompany" style="width:50%" type="text">&nbsp;<button id="addnonchcompany">Add Non-CH Company Directly</button>
<table id="companies" style="table-layout: fixed; width: 100%" class="table table-striped table-bordered table-hover">
<tr>
<th>Number</th>
<th><a class="columnHeading" data-column-number="2">Name</a></th>
<th><a class="columnHeading" data-column-number="6">Added</a></th>
<th>Details</th>
<th>Action</th>
</tr>
</table>

<ul class="pager">
<li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
<li class="next" id="next"><a href="#">Next &rarr;</a></li>
</ul>

<script>
$(document).ready(function() {
	$('button#addnonchcompany').click(function () {
		var companyName = $('input#addnonchcompany').val();
		$.ajax({
			url: '/ajax/upload-company',
			type: 'POST',
			data: {name: companyName, nonch: true},
			success: function() {
				location.reload();
			}
		});
	});
	
	$('button#addsinglecompany').click(function () {
		var companyName = $('input#addsinglecompany').val();
		$.ajax({
			url: '/ajax/upload-company',
			type: 'POST',
			data: {name: companyName},
			success: function() {
				location.reload();
			}
		});
	});
});
</script>
