<script src="/js/jquery-file-upload/js/vendor/jquery.ui.widget.js"></script>
<script src="/js/jquery-file-upload/js/jquery.iframe-transport.js"></script>
<script src="/js/jquery-file-upload/js/jquery.fileupload.js"></script>

<script>

$(document).ready(function() {

	netsensia_Pager(
			1,
			500,
			'company-owners',
			'/ajax/company-owners/list',
			function(key, value) {
				var url = '/directories/people/' + value.internalId;
				var newRow = '<tr>';
				newRow += '<td><a href="' + url + '">' + value.company + '</a></td>';
				newRow += '<td>' + value.owner + '</td>';
				newRow += '<td>' + prettyDate(value.requestdate) + '</td>';
				newRow += '<td>' + value.status + '</td>';
				newRow += '</tr>';
		
				return newRow;
			}
		);	

});

</script>