<div class="row">
<div class="col-md-12">

				<table class="table">
				<caption>Metrics &amp; Financials</caption>
              
						<tr><td>Incorporation Date</td><td><?php echo $this->incorporationdate; ?></td>	</tr>
						<tr><td>Closure Date</td><td><?php echo $this->closuredate; ?></td>	</tr>
						<tr><td>Company Status</td><td><?php echo $this->companystatus; ?></td>	</tr>
						<tr><td>Country of Origin</td><td><?php echo $this->countryoforigin; ?></td>	</tr>
						<tr><td>Exchange</td><td><?php echo $this->exchange; ?></td>	</tr>
						<tr><td>Company Category</td><td><?php echo $this->companycategory; ?></td>	</tr>
						<tr><td>Trading Symbol</td><td><?php echo $this->tradingsymbol; ?></td>	</tr>
						<tr><td>Number of Employees</td><td><?php echo $this->employeerange; ?></td>	</tr>
						<tr><td>Date of Employee Count</td><td><?php echo $this->employeecountdate; ?></td>	</tr>
						<tr><td>Company Revenue</td><td><?php echo $this->revenuerange; ?></td>	</tr>
						<tr><td>Year of Reported Revenue</td><td><?php echo $this->revenueyear; ?></td>	</tr>
						<tr><td>Revenue Growth %</td><td><?php echo $this->revenuegrowthrange; ?></td>	</tr>
						<tr><td>Year of Revenue Growth</td><td><?php echo $this->revenuegrowthyear; ?></td>	</tr>
						<tr><td>Financial Year End</td><td><?php echo $this->financialyearend; ?></td>	</tr>
						<tr>
						  <td>Previous Names</td>
						  <td>
						  <?php
						      foreach($this->pastnames as $pastname) {
						          echo $pastname['companypastname'] . '<br>';
						      } 
						  ?>
						  </td>
						</tr>
						<tr><td>Company Phase/Size</td><td><?php echo $this->companyphase; ?></td>	</tr>
						<tr><td>Company Ranking</td><td><?php echo $this->companyranking; ?></td>	</tr>
						<tr><td>Company Profit</td><td><?php echo $this->companyprofit; ?></td>	</tr>
						<tr><td>Investment Status</td><td><?php echo $this->investmentstatus; ?></td>	</tr>
						<tr>
						  <td>Patents</td>
						  <td>
						  <?php
						      foreach($this->patents as $patent) {
						          echo $patent['companypatent'] . '<br>';
						      } 
						  ?>
						  </td>
						</tr>
					
            </table>

</div>
</div>

