<div class="row">
<div class="col-md-12">

				<table class="table">
				<caption>Metrics &amp; Financials</caption>
              
						<tr><td>Incorporation Date</td><td><?php echo $this->incorporationdate; ?></td>	</tr>
						<tr><td>Closure Date</td><td><?php echo $this->closuredate; ?></td>	</tr>
						<tr><td>Company Status</td><td></td>	</tr>
						<tr><td>Country of Origin</td><td></td>	</tr>
						<tr><td>Exchange</td><td></td>	</tr>
						<tr><td>Company Category</td><td></td>	</tr>
						<tr><td>Trading Symbol</td><td><?php echo $this->tradingsymbol; ?></td>	</tr>
						<tr><td>Number of Employees</td><td><?php echo $this->employeerange; ?></td>	</tr>
						<tr><td>Date of Employee Count</td><td></td>	</tr>
						<tr><td>Company Revenue</td><td><?php echo $this->revenuerange; ?></td>	</tr>
						<tr><td>Year of Reported Revenue</td><td><?php echo $this->revenueyear; ?></td>	</tr>
						<tr><td>Revenue Growth %</td><td><?php echo $this->revenuegrowthrange; ?></td>	</tr>
						<tr><td>Year of Revenue Growth</td><td><?php echo $this->revenuegrowthyear; ?></td>	</tr>
						<tr><td>Financial Year End</td><td></td>	</tr>
						<tr><td>Previous Names</td><td></td>	</tr>
						<tr><td>Company Phase/Size</td><td></td>	</tr>
						<tr><td>Company Ranking</td><td></td>	</tr>
						<tr><td>Company Profit</td><td></td>	</tr>
						<tr><td>Investment Status</td><td></td>	</tr>
						<tr><td>Patents</td><td></td>	</tr>
					
            </table>

</div>
</div>

