<div class="row">
<div class="col-md-12">
    <table class="table" id="currentdirectors">
    <caption>Current Directors</caption>
    <?php if (isset($this->officers)) : ?>
              <?php $officerCount = 0; ?>
              <tr><th>Officer Name</th><th>Role</th></tr>
              <?php foreach ($this->officers as $officer) : ?>
              <tr>
						<td><a id="officer-id-<?php echo ++$officerCount ?>" href="/directories/people/<?php echo $officer['officerid']; ?>"><?php echo $officer['forename'] . ' ' . $officer['surname']; ?></a></td>
						<td><?php echo $officer['appointmenttype']; ?></td>
					</tr>
              <?php endforeach; ?>
              <?php endif; ?>
    </table>
    
    <table class="table" id="pastdirectors">
    <caption>Past Directors</caption>
    </table>
    </div>
</div>

