<div class="row">
	<div class="col-md-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Registered Address</h3>
			</div>
			<div class="panel-body">
            <?php
            $this->Address($this->registeredaddress);
            ?>
            <div id="registered-address-map"></div>
            </div>
		</div>
		
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Trading Address</h3>
			</div>
			<div class="panel-body">
            <?php
            $this->Address($this->tradingaddress);
            ?>
            <div id="trading-address-map"></div>
            </div>
		</div>
		
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Contact Details</h3>
			</div>
			<div class="panel-body">
            <table class="table">
					
					<tr>
						<td>Telephone</td>
						<td><?php echo $this->telephone; ?></td>
					</tr>
					<tr>
						<td>Fax</td>
						<td><?php echo $this->fax; ?></td>
					</tr>
					<tr>
						<td>Web</td>
						<td><?php echo $this->webaddress; ?></td>
					</tr>
				</table>
            </div>
		</div>

		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">Key Data</h3>
			</div>
			<div class="panel-body">
				<table class="table">
					<tr>
						<td>Sectors</td>
						<td><?php
                        echo trim($this->siccode1) == '' ? '' : ($this->siccode1 . '<br>');
                        echo trim($this->siccode2) == '' ? '' : ($this->siccode2 . '<br>');
                        echo trim($this->siccode3) == '' ? '' : ($this->siccode3 . '<br>');
                        echo trim($this->siccode4) == '' ? '' : ($this->siccode4 . '<br>');
                        ?></td>
					</tr>
					<tr>
						<td>Company Number</td>
						<td><?php echo $this->reference; ?></td>
					</tr>
					<tr>
						<td>Category</td>
						<td><?php echo $this->category; ?></td>
					</tr>
					<tr>
						<td>Incorporated</td>
						<td><?php echo $this->incorporationdate; ?></td>
					</tr>
					<tr>
						<td>Status</td>
						<td><?php echo $this->detailstatus; ?></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-8">

		<div class="row">
			<div class="col-md-6">
				<div class="panel panel-info">
					<div class="panel-heading">
						<h3 class="panel-title">News Feed</h3>
					</div>
					<div class="panel-body">
						<table class="table">
                    <?php
                    foreach ($this->bing as $bingResult) {
                        ?>
                        <tr>
								<td>
									<h5>
										<a href="<?php echo $bingResult['Url']; ?>"><?php echo $bingResult['Title']; ?></a>
									</h5>
									<div style="font-size: 0.8em; margin-bottom: 5px;">
                                    <?php
                        $timestamp = strtotime(
                            $bingResult['Date']);
                        $bingResult['Date'] = date(
                            'g:ia \o\n l jS F Y', 
                            $timestamp);
                        echo $bingResult['Date'];
                        ?>
                                </div>
                                <?php echo $bingResult['Description']; ?>
                            </td>
							</tr>

                    <?php
                    }
                    ?>
                    </table>
					</div>
				</div>
			</div>

			<div class="col-md-6">


				<div class="panel panel-info">
					<div class="panel-heading">
						<h3 class="panel-title">Twitter Feed</h3>
					</div>
					<div class="panel-body">
						<table class="table">
                    <?php
                    foreach ($this->tweets as $tweet) {
                        ?>
                        <tr>
								<td><img src="<?php echo $tweet['userimage']; ?>"></td>
								<td>
                                <?php echo $tweet['text']; ?>
                            </td>
							</tr>

                    <?php
                    }
                    ?>
                    </table>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>