<div class="row">
<div class="col-md-12">

				<table class="table">
				<caption>Related Companies</caption>
				<tr><th>Company</th><th>Relationship</th></tr>
              <?php foreach ($this->relatedCompanies as $relatedCompany) :?>
              <tr>
						<td><?php echo $relatedCompany['relatedcompany']; ?></td>
						<td><?php echo $relatedCompany['relationship']; ?></td>
					</tr>
              <?php endforeach; ?>
            </table>

</div>
</div>

