<div class="row">
<div class="col-md-12">

				<table class="table">
				<caption>Related Companies</caption>
				<tr><th>Company</th><th>Relationship</th></tr>
              <?php foreach ($this->relatedCompanies as $relatedCompany) :?>
              <tr>
						<td>
						<?php if ($relatedCompany['relatedcompanyid'] != 0): ?>
						<a href="/directories/company/<?php echo $relatedCompany['relatedcompanyid']; ?>">
						<?php echo $relatedCompany['relatedcompany']; ?>
						</a>
						<?php else: ?>
						  <?php echo $relatedCompany['relatedcompany']; ?>
						<?php endif; ?>
						</td>
						<td><?php echo $relatedCompany['relationship']; ?></td>
					</tr>
              <?php endforeach; ?>
            </table>

</div>
</div>

