<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Directorzone'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Styles -->
        <?php $cssVersion=102; ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/brand/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css?v=' . $cssVersion)
                        ->prependStylesheet($this->basePath() . '/css/datepicker.css')
                        ->prependStylesheet($this->basePath() . '/css/button-spinner.css')
                        ->prependStylesheet($this->basePath() . '/js/jquery-ui-1.10.3/themes/base/jquery-ui.css')
                        ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.0.1-p7/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/js/bootstrap3-editable-1.5.1/bootstrap3-editable/css/bootstrap-editable.css')
                        ->prependStylesheet($this->basePath() . '/js/bootstrap3-wysiwyg-master/dist/bootstrap3-wysihtml5.min.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                      ->prependFile($this->basePath() . '/js/pretty.js')
                      ->prependFile($this->basePath() . '/js/validate.min.js')
                      ->prependFile($this->basePath() . '/js/netsensia/pager.js')
                      ->prependFile($this->basePath() . '/js/netsensia/formwidget_hierarchy.js')
                      ->prependFile($this->basePath() . '/js/netsensia/formwidget_geography.js')
                      ->prependFile($this->basePath() . '/js/netsensia/formwidget_multitable.js')
                      ->prependFile($this->basePath() . '/js/bootstrap3-wysiwyg-master/dist/bootstrap3-wysihtml5.all.min.js')
                      ->prependFile($this->basePath() . '/js/bootstrap3-editable-1.5.1/bootstrap3-editable/js/bootstrap-editable.js')
                      ->prependFile($this->basePath() . '/js/application.js')
                      ->prependFile($this->basePath() . '/js/ajax-file-upload/ajaxFileUpload.js')
                      ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3/ui/minified/jquery-ui.min.js')
                      ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.0.1-p7/js/bootstrap.min.js')
                      ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js')
        ?>

</head>
<body>
    <input type="hidden" id="columnSorter" data-sort-by-column="1" data-tab="1">

    <div id="page-wrap">
        <div id="main">
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                
                    <div class="navbar-header">
                    
                        <img src="/img/brand/logo_and_text.fw.png">
                        <!--  <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                          <span class="directorzone-brand-type"><?php echo $this->translate('DIRECTORZONE') ?></span>
                        </a>-->

                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target=".navbar-collapse">
                            <span class="icon-bar"></span> <span class="icon-bar"></span> <span
                                class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                        <?php
                            $someurls = [
                                'home' => $this->translate("Home"),
                                'directories' => $this->translate("Directories"),
                                'articles/article-list' => $this->translate("Articles"),
                                'events-calendar' => $this->translate("Events"),
                            ];
                            if ($this->identity()) {
                                $moreurls = [];
                               //
                            } else {
                                if ($this->config()['netsensia']['enable-users']) {
                                    $moreurls = array(
                                        'home' => $this->translate("Home"),
                                    );
                                } else {
                                    $moreurls = array(
                                        'home' => $this->translate("Home"),
                                        'contact' => $this->translate("Contact"),
                                    );
                                }
                            }
                            $urls = array_merge($someurls, $moreurls); 
                        ?>
                        <?php foreach ($urls as $url => $name) { ?>
                             <li>
                                <a style="color:#fff" href="<?php echo $this->url($url); ?>"><?php echo $this->translate($name); ?></a></li>
                        <?php } ?>
                           <li><a style="color:#b94a48"><?php echo $this->translate('Anonymous') ?></a></li>
                           <li><a style="color:#3a87ad"><?php echo $this->translate('Public') ?></a></li>

                    </ul>
                    <?php if ($this->config()['netsensia']['enable-users']) { ?>
                    <?php if (!$this->identity()) { ?>
                        <ul class="nav navbar-nav pull-right">
                            <li class="dropdown"><a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('Sign In'); ?><b class="caret"></b></a>
                                <ul class="dropdown-menu" id="login-dropdown" aria-labelledby="drop3">
                                    <li>
                                        <form method="post" action="<?php echo $this->url('login'); ?>">
                                            <input type="text" style="margin: 10px;" name="login-email" class="form-control" placeholder="Email" /> 
                                            <input type="password" style="margin: 10px;" name="login-password" class="form-control" placeholder="Password" /> 
                                            <input type="checkbox" style="margin: 10px;" name="remember" value="remember" /> <?php echo $this->translate('Remember Me'); ?>
                                           <input type="submit"
                                                class="btn btn-primary" style="margin: 10px;" name="submit"
                                                value="<?php echo $this->translate('Sign In'); ?>">
                                        </form>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a tabindex="-1"
                                        href="<?php echo $this->url('register'); ?>"><?php echo $this->translate("Create a new account"); ?></a></li>
                                    <li class="divider"></li>
                                    <li><a tabindex="-1"
                                        href="<?php echo $this->url('password-reset'); ?>"><?php echo $this->translate("Reset your password"); ?></a></li>
                                </ul>
                            </li>
                            
                        </ul>
                        <?php } else { ?>
                         <?php $user = $this->identity(); ?>
                        <ul class="nav navbar-nav pull-right">
                            <li class="dropdown"><a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->escapeHtml($user->getName()); ?><b class="caret"></b></a>
                                <ul class="dropdown-menu" id="login-dropdown" aria-labelledby="drop3">
                                    <li><a href="<?php echo $this->url('myaccount') ?>"><?php echo $this->translate('Account') ?></a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('Logout') ?></a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
                                   </ul>
                            </li>
                            
                        </ul>

                        <?php } ?>
                        <?php } ?>
                        <div class="visible-lg">
                        <form action="/search" class="navbar-form navbar-right" role="search">
                            <div class="form-group">
                                <input type="text" name="keywords" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </form>
                        </div>       
                    </div>
                </div>
            </nav>

<div class="container">
                                    <div class="visible-xs visible-sm visible-md">
                        <form action="/search" class="navbar-form navbar-right" role="search">
                            <div class="form-group">
                                <input type="text" name="keywords" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </form>
                        </div> 
                        </div>
                        
            <div class="container">
            
            
            <?php 
            // First get the viewmodel and all its children (ie the actions viewmodel)
            $children = $this->viewModel()->getCurrent()->getChildren();
            
            if (is_array($children) && count($children) > 0) {
            
                $ourView  = $children[0];
                
                $variables = $ourView->getVariables();
                
                if (isset($variables['flashMessages']) && count($variables['flashMessages']) > 0) :
            ?>
            <div class="container">
                 <?php foreach ($variables['flashMessages'] as $fMessage) : ?>
                    <?php $alertType = 'block'; ?>
                    <?php if (preg_match('/^(.*)##(.*)$/', $fMessage, $matches)) { $fMessage = $matches[1]; $alertType = $matches[2]; } ?>
                    <div class="alert alert-<?php echo $alertType; ?>">
                        <button type="button" class="close" data-dismiss="alert">&times;</button> 
                    <?php echo $fMessage; ?>
                    </div>
                    <?php endforeach; ?>
             </div>  
                <?php endif; ?>
            <?php 
            }
            ?>
            
            <?php echo $this->content; ?>
            
        </div>
            <!-- /container -->
        </div>
    </div>

    <footer id="footer">
        <div class="container">
            <p>&copy; 1999 - <?php echo date('Y') ?> by Directorzone Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            <ul class="footer-links">
                <li><a href="<?= $this->url('home'); ?>"><?= $this->translate('Home'); ?></a></li>
                <li class="muted">&middot;</li>
                <li><a href="<?= $this->url('contact'); ?>"><?= $this->translate('Feedback'); ?></a></li>
                <li class="muted">&middot;</li>
                <li><a href="<?= $this->url('help'); ?>"><?= $this->translate('Help'); ?></a></li>
                <li class="muted">&middot;</li>
                <li><a href="<?= $this->url('admin'); ?>"><?= $this->translate('Admin'); ?></a></li>
            </ul>
            <ul class="footer-links">
            <li>Build number <strong><?php echo file_exists('build/build_number.txt') ? file_get_contents('build/build_number.txt') : '' ?></strong></li>
            <li>@ <?php echo file_exists('build/build_number.txt') ? file_get_contents('build/build_time.txt') : '' ?></li>
            </ul>
        </div>

    </footer>
       

        <?php echo $this->inlineScript() ?>
    </body>

</html>
