<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Directorzone'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/brand/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/datepicker.css')
                        ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.0.1-p7/css/bootstrap.min.css')
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.0.1-p7/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/validate.min.js')
                                      ->prependFile($this->basePath() . '/js/application.js')
                                      ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3/ui/minified/jquery-ui.min.js')
                                      ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js')
                                      
                                      ?>

</head>
<body>
	<div id="page-wrap">
		<div id="main">
			<nav class="navbar navbar-inverse navbar-fixed-top">
				<div class="container">
					<div class="navbar-header">
						<a class="navbar-brand" href="<?php echo $this->url('home') ?>">
						  <span class="directorzone-brand-type"><?php echo $this->translate('DIRECTORZONE') ?></span>
						</a>

						<button type="button" class="navbar-toggle" data-toggle="collapse"
							data-target=".navbar-collapse">
							<span class="icon-bar"></span> <span class="icon-bar"></span> <span
								class="icon-bar"></span>
						</button>
					</div>
					<div class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
                        <?php
                        	$someurls = [
								'home' => $this->translate("Home"),
								'directories' => $this->translate("Directories"),
								'content' => $this->translate("Content"),
                                'admin' => $this->translate("Admin"),
                        	];
                            if ($this->identity()) {
                                $moreurls = array(
                                    'contact' => $this->translate("Contact")
                                );
                            } else {
                                if ($this->config()['netsensia']['enable-users']) {
                                    $moreurls = array(
                                        'home' => $this->translate("Home"),
                                        'register' => $this->translate("Register"),
                                        'contact' => $this->translate("Contact"),
                                    );
                                } else {
                                    $moreurls = array(
                                        'home' => $this->translate("Home"),
                                        'contact' => $this->translate("Contact"),
                                    );
                                }
                            }
                            $urls = array_merge($someurls, $moreurls); 
                        ?>
                        <?php foreach ($urls as $url => $name) { ?>
                            <li
								class="<?php echo ($this->url() == $this->url($url) ? "active" : ""); ?>"><a
								href="<?php echo $this->url($url); ?>"><?php echo $this->translate($name); ?></a></li>
                            <?php } ?>
                            <?php if ($user = $this->identity()) { ?>
                            <li><a href="<?php echo $this->url('myaccount') ?>"><?php echo $this->translate('My Account') ?></a></li>
                            
                            <li><a href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('Logout') ?></a></li>
							
                        <?php } ?>
                    </ul>
                    <?php if ($this->config()['netsensia']['enable-users']) { ?>
                    <?php if (!$this->identity()) { ?>
                        <ul class="nav navbar-nav pull-right">
							<li class="dropdown"><a href="#" id="drop3" role="button"
								class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('Sign In / Sign Up'); ?><b
									class="caret"></b></a>
								<ul class="dropdown-menu" id="login-dropdown" aria-labelledby="drop3">
									<li>
										<form method="post" action="<?php echo $this->url('login'); ?>">
											<input type="text" style="margin: 10px;" name="login-email" class="form-control" placeholder="Email" /> 
											<input type="password" style="margin: 10px;" name="login-password" class="form-control" placeholder="Password" /> 
											<input type="checkbox" style="margin: 10px;" name="remember" value="remember" /> <?php echo $this->translate('Remember Me'); ?>
                                	       <input type="submit"
												class="btn btn-primary" style="margin: 10px;" name="submit"
												value="<?php echo $this->translate('Sign In'); ?>">
										</form>
									</li>
									<li class="divider"></li>
									<li><a tabindex="-1"
										href="<?php echo $this->url('register'); ?>"><?php echo $this->translate("Create a new account"); ?></a></li>
									<li class="divider"></li>
									<li><a tabindex="-1"
										href="<?php echo $this->url('password-reset'); ?>"><?php echo $this->translate("Reset your password"); ?></a></li>
								</ul>
							</li>
							
						</ul>
                        <?php } else { ?>
                        <ul class="nav navbar-nav pull-right">
						<li><a><strong><?php echo $this->escapeHtml($user->getName()); ?></strong></a></li>
						</ul>
						<?php } ?>
						<?php } ?>
                        <form class="navbar-form navbar-right" role="search">
							<div class="form-group">
								<input type="text" class="form-control" placeholder="Search">
							</div>
							<button type="submit" class="btn btn-default">Submit</button>
						</form>						
					</div>
				</div>
			</nav>



			<div class="container">
            
            <?php 
            // First get the viewmodel and all its children (ie the actions viewmodel)
            $children = $this->viewModel()->getCurrent()->getChildren();
            
            $ourView  = $children[0];
            
            $variables = $ourView->getVariables();
            
            if (isset($variables['flashMessages']) && count($variables['flashMessages']) > 0) : ?>
             <?php foreach ($variables['flashMessages'] as $fMessage) : ?>
                <?php $alertType = 'block'; ?>
                <?php if (preg_match('/^(.*)##(.*)$/', $fMessage, $matches)) { $fMessage = $matches[1]; $alertType = $matches[2]; } ?>
                <div class="alert alert-<?php echo $alertType; ?>">
					<button type="button" class="close" data-dismiss="alert">&times;</button> 
                <?php echo $fMessage; ?>
                </div>
                <?php endforeach; ?>  
            <?php endif; ?>
                    
            <?php echo $this->content; ?>
            
        </div>
			<!-- /container -->
		</div>
	</div>

	<footer id="footer">
		<div class="container">
			<p>&copy; 1999 - <?php echo date('Y') ?> by Directorzone Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
			<ul class="footer-links">
				<li><a href="<?= $this->url('home'); ?>"><?= $this->translate('Home'); ?></a></li>
				<li class="muted">&middot;</li>
				<li><a href="<?= $this->url('contact'); ?>"><?= $this->translate('Feedback'); ?></a></li>
				<li class="muted">&middot;</li>
				<li><a href="<?= $this->url('help'); ?>"><?= $this->translate('Help'); ?></a></li>
			</ul>
			<ul class="footer-links">
				<li><a
					href="<?php echo $this->url('locale', ["locale"=>"en_GB"]); ?>"><?php echo $this->translate('English'); ?></a>
				
				<li class="muted">&middot;</li>
				<li><a
					href="<?php echo $this->url('locale', array("locale"=>"fr_FR")); ?>"><?php echo $this->translate('French'); ?></a>
			
			</ul>
		</div>

	</footer>
       

        <?php echo $this->inlineScript() ?>
    </body>

</html>
