<body>
    <ul class="breadcrumb">
      <li>
        <a href="/">Home</a>
      </li>
      <li>
        <a href="/article/list">Articles</a>
      </li>
      <li class="active">
        <?php echo $this->title; ?>
      </li>
    </ul>

    <div style="min-height:30em">
    
      <?php foreach ($this->sectors as $sectorId => $sectorName): ?>
      <span class="badge"><?php echo $sectorName ?></span>
      <?php endforeach; ?>

      <h5>
        <a href="/article/<?php echo $this->articleid ?>/edit">Edit this article</a> | 
        <a id="deletearticle" href="/article/<?php echo $this->articleid ?>/delete">Delete this article</a> |
        <a href="#" id="sendmessagedialog" data-id="<?php echo $this->userid; ?>">Reply to author</a> |
        <?php $addCommentLink = '<a href="#" id="addcommentdialog" data-id="' . $this->articleid . '">Add a comment</a>'; ?>
        <?php echo $addCommentLink; ?>
      </h5>

      <?php echo $this->partial('messaging/dialog.phtml'); ?>
      <?php echo $this->partial('comments/dialog.phtml'); ?>

      <h3>
        <?php echo $this->title; ?>
      </h3>
      <div>
        Published by <?php echo $this->pseudonym; ?>
      </div>
      <p>
      <div class="col-xs-6 col-md-2" style="padding:0.5em">
            <img class="img-thumbnail" src="<?php echo $this->image; ?>">
      </div>
  
        
        <?php echo $this->BbCode($this->content); ?>
      </p>
    </div>
  
  <?php echo $this->ArticleComments($this->comments, $addCommentLink); ?>

</body>

<script>
$(document).ready(function() {
    $('#deletearticle').click(function() {
        return confirm('Do you want to delete this article?');
    });
});
</script>


