<body>
    <ul class="breadcrumb">
      <li>
        <a href="/">Home</a>
      </li>
      <li>
        <a href="/article/list">Articles</a>
      </li>
      <li class="active">
        <?php echo $this->title; ?>
      </li>
    </ul>

    <div style="min-height:30em">
    
      <?php foreach ($this->sectors as $id => $name): ?>
      <span class="badge"><?php echo $name ?></span>
      <?php endforeach; ?>
      
      <?php foreach ($this->geographies as $id => $name): ?>
      <span class="badge"><?php echo $name ?></span>
      <?php endforeach; ?>
      
      <?php foreach ($this->keyevents as $id => $name): ?>
      <span class="badge"><?php echo $name ?></span>
      <?php endforeach; ?>
      
      <?php foreach ($this->jobareas as $id => $name): ?>
      <span class="badge"><?php echo $name ?></span>
      <?php endforeach; ?>
      
      <h5>
        <a href="/article/<?php echo $this->articleid ?>/edit">Edit this article</a> | 
        <a id="deletearticle" href="/article/<?php echo $this->articleid ?>/delete">Delete this article</a> |
        <a href="#" id="sendmessagedialog" data-id="<?php echo $this->userid; ?>">Reply to author</a> |
        <?php $addCommentLink = '<a href="#" id="addcommentdialog" data-id="' . $this->articleid . '">Add a comment</a>'; ?>
        <?php echo $addCommentLink; ?>
      </h5>

      <?php echo $this->partial('messaging/dialog.phtml'); ?>
      <?php echo $this->partial('comments/dialog.phtml'); ?>

      
      <hr>
      
      <div>
          <h3>
            <?php echo $this->title; ?>
          </h3>
      </div>
      <hr>
      
      <div>
      <?php $this->ArticleAuthor(); ?>
      </div>
      
      <?php // $this->ArticleFields(); ?>

       <div style="clear:both">
        <img style="float:left;margin-right:1em;height:150px;width:150px" src="<?php echo $this->image; ?>">
       
        <?php echo $this->content; ?>
        </div> 
    </div>
  
  <?php  $this->ArticleComments($this->comments, $addCommentLink); ?>

</body>

<script>
$(document).ready(function() {
    $('#deletearticle').click(function() {
        return confirm('Do you want to delete this article?');
    });
});
</script>


