<h3><?php echo $this->forename . ' ' . $this->surname; ?></h3>
<h5>
	<a href="/directories/people/<?php echo $this->officerid; ?>/feeds">Edit
		this person</a>
</h5>

<div class="row">
	<div class="col-md-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Target Roles</h3>
			</div>
			<div class="panel-body"></div>
		</div>

		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">Expertise</h3>
			</div>
			<div class="panel-body"></div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Personal Summary</h3>
			</div>
			<div class="panel-body">
            <?php
            echo $this->talentpoolsummary;
            ?>
            </div>
		</div>
		<div class="panel panel-primary">

			<div class="panel-heading">
				<h3 class="panel-title">Skills Summary</h3>
			</div>
			<div class="panel-body">
            <?php
            echo $this->talentpoolsummaryskills;
            ?>
            </div>
		</div>

		<div class="panel panel-primary">

			<div class="panel-heading">
				<h3 class="panel-title">Experience Summary</h3>
			</div>
			<div class="panel-body">
            <?php
            echo $this->talentpoolsummaryexperience;
            ?>
            </div>
		</div>

		<div class="panel panel-primary">

			<div class="panel-heading">
				<h3 class="panel-title">Summary of Interests</h3>
			</div>
			<div class="panel-body">
            <?php
            echo $this->talentpoolsummaryinterests;
            ?>
            </div>
		</div>


		<div class="row">
			<div class="col-md-6">
				<div class="panel panel-info">
					<div class="panel-heading">
						<h3 class="panel-title">Key Facts</h3>
					</div>
					<div class="panel-body"></div>
				</div>
			</div>

			<div class="col-md-6">


				<div class="panel panel-info">
					<div class="panel-heading">
						<h3 class="panel-title">Blog Posts</h3>
					</div>
					<div class="panel-body"></div>
				</div>

			</div>
		</div>
	</div>
</div>
</div>

