<?php echo $this->partial('account-nav.phtml'); ?>
<?php echo $this->BootstrapForm($this->form, 'Career Experience', $this->url('account-experience')); ?>

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.27/angular.min.js"></script>

<div ng-app="experience" ng-controller="ExperienceController as experience">
    <input placeholder="Search for a company" class="companyname" ng-model="experience.companyname" ng-change="experience.autocomplete()" type="text" style="width: 66%;">
  
    <div ng-repeat="company in experience.companies">
        <div style="font-size:1em;font-weight:bold">{{ company.name }}</div>
        <div style="font-size:0.8em">
        {{ company.category }}, {{ company.detailstatus }}
        </div>
        <div style="font-size:0.8em">
        Company number: {{ company.number }}, Address: {{ company.addressline1 }}, {{ company.town }}, {{ company.postcode }}
        </div>

    </div>
</div>
    
<script src="/js/angular/modules/experience.js"></script>
