<?php echo $this->partial('account-nav.phtml'); ?>

<?php echo $this->partial('messaging/dialog.phtml', [
        'messageTitle' => '',
        'messageRecipient' => ''
    ]); 
?>

<?php if ($this->isArchive == 'Y'): ?>
    <h3>My Inbox (archive)</h3>
    <a href="/myaccount/inbox/page/1?isArchive=N">View Inbox</a>
    
<?php else: ?>
    <h3>My Inbox</h3>
    <a href="/myaccount/inbox/page/1?isArchive=Y">View Inbox Archive</a>
<?php endif; ?>


<table id="inbox" data-link="row" class=" table table-striped table-bordered table-hover">
<tr>
<th><a class="columnHeading" data-column-number="1">From</a></th>
<th><a class="columnHeading" data-column-number="2">Title</a></th>
<th><a class="columnHeading" data-column-number="3">Sent</a></th>
<th>Actions</th>
</tr>
</table>

<ul class="pager">
<li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
<li class="next" id="next"><a href="#">Next &rarr;</a></li>
</ul>

<script>

$(document).ready(function() {
	$('#columnSorter').attr('data-sort-by-column', -3);
	
	$(document).delegate('.columnHeading', 'click', function() {
		loadTheTable();
	});
    loadTheTable();
});

function loadTheTable() {
	netsensia_Pager(
			<?php echo $this->startPage; ?>,
			20,
			'inbox',
			'/ajax/inbox/list?isArchive=<?php echo $this->isArchive; ?>',
			function(key, value) {
				var url = '/myaccount/inbox/' + value.internalId;

				var flagText = value.isFlagged == 'Y' ? '<a href="#" id="unflagmessage" data-messageid="' + value.internalId + '">Unflag</a>' : '<a href="#" id="flagmessage" data-messageid="' + value.internalId + '">Flag</a>';
				var archiveText = value.isArchived == 'Y' ? '<a href="#" id="unarchivemessage" data-messageid="' + value.internalId + '">Unarchive</a>' : '<a href="#" id="archivemessage" data-messageid="' + value.internalId + '">Archive</a>';
				var deleteText = '<a href="#" id="deletemessage" data-messageid="' + value.internalId + '">Delete</a>';
				var actions = flagText + ' | ' + archiveText + ' | ' + deleteText;
			    
				var newRow = '<tr>';
				newRow += '<td><a data-messageid="' + value.internalId + '" href="' + url + '">' + value.from + '</a></td>';
				newRow += '<td><a data-messageid="' + value.internalId + '" href="' + url + '">' + value.title + '</a></td>';
				newRow += '<td class="prettydate">' + prettyDate(value.senttime) + '</td>';
				newRow += '<td>' + actions + '</td>';
				newRow += '</tr>';
		
				return newRow;
			}
		);
}
</script>
