<?php echo $this->partial('account-nav.phtml'); ?>
<h3>My Articles</h3>

<div class="well well-sm">
<span article-type="1" style="cursor:pointer" class="type-label label label-primary">Blog Posts</span>
<span article-type="2" style="cursor:pointer" class="type-label label label-primary">News Articles</span>
<span article-type="3" style="cursor:pointer" class="type-label label label-primary">Wanted</span>
<span article-type="4" style="cursor:pointer" class="type-label label label-primary">Offered</span>
<span article-type="5" style="cursor:pointer" class="type-label label label-primary">Events</span>
<span article-type="6" style="cursor:pointer" class="type-label label label-primary">Meeting Requests</span>
<span article-type="7" style="cursor:pointer" class="type-label label label-primary">Opportunities</span>
<span article-type="8" style="cursor:pointer" class="type-label label label-primary">Movers</span>
</div>

<div class="well well-sm">
<span article-status="1" style="cursor:pointer" class="status-label label label-primary">Unapproved</span>
<span article-status="2" style="cursor:pointer" class="status-label label label-primary">Approved</span>
<span article-status="3" style="cursor:pointer" class="status-label label label-default">Rejected</span>
<span article-status="4" style="cursor:pointer" class="status-label label label-default">Hidden</span>
</div>

<table id="articles" data-link="row" class="rowlink table table-striped table-bordered table-hover">
<tr>
<th><a class="columnHeading" data-column-number="1">Title</a></th>
<th><a class="columnHeading" data-column-number="2">Author</a></th>
<th><a class="columnHeading" data-column-number="3">Published</a></th>
<th><a class="columnHeading" data-column-number="4">Sectors</a></th>
</tr>
</table>

<ul class="pager">
<li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
<li class="next" id="next"><a href="#">Next &rarr;</a></li>
</ul>

<script>

$(document).ready(function() {
	var typeArray = ["1","2","3","4","5","6","7","8"];
	var statusArray = ["1", "2"];
	
	$(document).delegate('.columnHeading', 'click', function() {
		loadArticles(typeArray, statusArray);
	});
	
    loadArticles(typeArray, statusArray);

    $('.type-label').click(function() {
        
        var articleType = $(this).attr('article-type');
        var index = typeArray.indexOf(articleType);
        if (index == -1) {
            typeArray.push(articleType);
            $('span[article-type=' + articleType + ']').addClass('label-primary');
            $('span[article-type=' + articleType + ']').removeClass('label-default');
        } else {
            typeArray.splice(index, 1);
            $('span[article-type=' + articleType + ']').removeClass('label-primary');
            $('span[article-type=' + articleType + ']').addClass('label-default');

        }
        
        loadArticles(typeArray, statusArray);
        return false;
        
    });

    $('.status-label').click(function() {
        var articleStatus = $(this).attr('article-status');
        var index = statusArray.indexOf(articleStatus);
        if (index == -1) {
            statusArray.push(articleStatus);
            $('span[article-status=' + articleStatus + ']').addClass('label-primary');
            $('span[article-status=' + articleStatus + ']').removeClass('label-default');
        } else {
        	statusArray.splice(index, 1);
            $('span[article-status=' + articleStatus + ']').removeClass('label-primary');
            $('span[article-status=' + articleStatus + ']').addClass('label-default');

        }
        
        loadArticles(typeArray, statusArray);
        return false;
        
    });
});

function loadArticles(typeArray, statusArray) {

	var typeParam = '';
	for (var i = 0; i < typeArray.length; i++) {
	    typeParam += 'type[]=' + typeArray[i];
	    if (i+1 < typeArray.length) {
		    typeParam += '&';
	    }
	}

	var statusParam = '';
	for (var i = 0; i < statusArray.length; i++) {
		statusParam += 'status[]=' + statusArray[i];
	    if (i+1 < statusArray.length) {
	    	statusParam += '&';
	    }
	}

	url = '/ajax/article/list?' + typeParam + '&' + statusParam + '&onlyme=1';
    
	netsensia_Pager(
			1,
			20,
			'articles',
			url,
			function(key, value) {
				var url = '/article/' + value.internalId;
				var newRow = '<tr>';
				newRow += '<td><a href="' + url + '">' + value.title + '</a></td>';
				newRow += '<td>' + value.author + '</td>';
				newRow += '<td>' + value.publishdate + '</td>';
				newRow += '<td>&nbsp;</td>';
				newRow += '</tr>';
		
				return newRow;
			}
		);
}
</script>
