<?php echo $this->partial('account-nav.phtml'); ?>

<?php if (strlen(trim($this->footprint)) > 10): ?>
<div class="container" id="talentpooleditheadline">
	<div class="row">
		<div class="col-md-12">
			<div class="well well-sm">
				<div>
					<strong><?php echo $this->footprint; ?></strong>
				</div>
				<div>
<?php echo $this->talentpoolsummary; ?>
</div>
			</div>
		</div>
	</div>
</div>
<?php endif; ?>
<?php echo $this->BootstrapForm($this->form, 'Talent Pool Profile', $this->url('account-profile')); ?>
