<style>
.sceditor-button {
	width:24px;
	height:24px;
}

textarea {
	min-height:125px;
}
</style>

<?php echo $this->partial('account-nav.phtml'); ?>

<?php 
    echo $this->BootstrapForm(
        $this->form,
        'Publishing Dashboard',
        $this->url(null, ['id'=>$this->editId]),
        ['showAdminFields' => $this->isAdmin]
    );
?>

<script>

$(function() {

    // Replace all textareas
    // with SCEditor
    $("textarea").each(function() {
        $(this).wysihtml5();
    });

    dateVisibility('none');
    locationVisibility('none');
    isAnonymousVisibility('none');

    var display;

    setVisibilities($("#account-publish-articlecategory"));
    
    $("#account-publish-articlecategory").change(function() {
        setVisibilities($(this));
    });

    function setVisibilities(obj) {
    	var val = obj.val();

        if (val == 5 || val == 6) {
            display = 'block';
        } else {
            display = 'none';
        }
        dateVisibility(display);
        locationVisibility(display);
        isAnonymousVisibility(val == 7 ? 'block' : 'none');
    }
});

function isAnonymousVisibility(display)
{
    $("[data-netsensia-group='account-publish-isanonymous']").css('display', display);
}

function dateVisibility(display)
{
    $("[data-netsensia-group='account-publish-startdate']").css('display', display);
    $("[data-netsensia-group='account-publish-enddate']").css('display', display);
}

function locationVisibility(display)
{
    $("[data-netsensia-group='account-publish-location']").css('display', display);
}

$(document).delegate('select[id^=netsensiaWidget_hierarchy]', 'change', function(event) {
	var selectedId = $(this).val();
	if (<?php echo !$this->hasCompany ?> && (selectedId == 18 || selectedId == 20)) {
		if ($('#no-company-warning').length == 0) {
			  $('.hierarchy-widget-group').parent().append(
				  '<div id="no-company-warning" class="bs-callout bs-callout-danger bs-callout-overview">' +
				  'You do not currently have any companies associated with your account. You can associate your account with a company ' +
				  'on the profile page of any company. If your company is not in our directory, you can add it via your personal profile.' +
				  '</div>'
			  );
		}
		$(this).val(-1);
		event.stopPropogation();
		return false;
	}
});

</script>
