<link rel="stylesheet" href="/js/sceditor/minified/themes/default.min.css" type="text/css" media="all" />
<script type="text/javascript" src="/js/sceditor/minified/jquery.sceditor.bbcode.min.js"></script>

<style>
.sceditor-button {
	width:24px;
	height:24px;
}

textarea {
	min-height:125px;
}
</style>

<?php echo $this->partial('account-nav.phtml'); ?>

<?php 
    echo $this->BootstrapForm(
        $this->form,
        'Publishing Dashboard',
        $this->url(null, ['id'=>$this->editId]),
        ['showAdminFields' => $this->isAdmin]
    );
?>

<script>
$(function() {
    // Replace all textareas
    // with SCEditor
    $("textarea").sceditor({
       plugins: "bbcode",
        style: "/js/sceditor/minified/jquery.sceditor.default.min.css"
    });

    dateVisibility('none');
    locationVisibility('none');
    isAnonymousVisibility('none');

    var display;

    $("#account-publish-articlecategory").change(function() {
        var val = $(this).val();

        if (val == 5 || val == 6) {
            display = 'block';
        } else {
            display = 'none';
        }
        dateVisibility(display);
        locationVisibility(display);
        isAnonymousVisibility(val == 7 ? 'block' : 'none');
    });
});

function isAnonymousVisibility(display)
{
    $("[data-netsensia-group='account-publish-isanonymous']").css('display', display);
}

function dateVisibility(display)
{
    $("[data-netsensia-group='account-publish-startdate']").css('display', display);
    $("[data-netsensia-group='account-publish-enddate']").css('display', display);
}

function locationVisibility(display)
{
    $("[data-netsensia-group='account-publish-location']").css('display', display);
}
</script>