<?php echo $this->partial('account-nav.phtml'); ?>
<?php echo $this->partial('messaging/dialog.phtml', [
        'messageTitle' => 'Re: ' . $this->title,
        'messageRecipient' => $this->from
    ]); 
?>
<h3><?php echo $this->title ?></h3>
<hr>
From: <?php
    $link = $this->url('directories/talent-pool/talent-pool-details', ['id' => $this->senderid]); 
    echo '<a href="' . $link . '">' . $this->from . '</a>'; 
?>
<hr>
<a href="#" id="sendmessagedialog" data-id="<?php echo $this->senderid; ?>" data-name="<?php echo $this->from; ?>">Reply</a> | 
<a href="#" id="forwardmessagedialog">Forward</a> | 
<a href="#" id="deletemessage" data-messageid="<?php echo $this->usermessageid; ?>">Delete</a> |

<?php if ($this->isarchived == 'N'): ?>
<a href="#" id="archivemessage" data-messageid="<?php echo $this->usermessageid; ?>">Archive</a> |
<?php else: ?>
<a href="#" id="unarchivemessage" data-messageid="<?php echo $this->usermessageid; ?>">Move to inbox</a> |
<?php endif; ?> 

<?php if ($this->isflagged == 'N'): ?>
<a href="#" id="flagmessage" data-messageid="<?php echo $this->usermessageid; ?>">Flag</a>
<?php else: ?>
<a href="#" id="unflagmessage" data-messageid="<?php echo $this->usermessageid; ?>">Unflag</a>
<?php endif; ?> 

<hr>

<?php echo $this->content; ?>

<script>

$(document).ready(function() {

});

</script>
