<table border="1" style="width:100%">
<tr><td>Number</td><td><?php echo $this->company->getCompanyNumber(); ?></td></tr>
<tr><td>Name</td><td><?php echo $this->company->getCompanyName(); ?></td></tr>

<tr><td>Address</td>
<td>
    <?php 
        foreach ($this->company->getAddressLines() as $line) {
            echo $line . '<br>';
    }?>
    
    Postcode: <?php echo $this->company->getPostcode(); ?>
</td></tr>

<tr><td>Category</td><td><?php echo $this->company->getCategory(); ?></td></tr>
<tr><td>Status</td><td><?php echo $this->company->getStatus(); ?></td></tr>
<tr><td>Country</td><td><?php echo $this->company->getCountry(); ?></td></tr>
<tr><td>Incorporation Date</td><td><?php echo $this->company->getIncorporationDate(); ?></td></tr>

<tr><td>Number of Current Appointments</td><td><?php echo $this->appointments->getNumberOfCurrentAppointments(); ?></td></tr>
<tr><td>Number of Resigned Appointments</td><td><?php echo $this->appointments->getNumberOfResignedAppointments(); ?></td></tr>

<tr>
    <td>Accounts</td>
    <td>
        <table>
            <tr><td>Category</td><td><?php echo $this->company->getAccountsDetails()->getCategory(); ?></td></tr>
            <tr><td>Ref Date</td><td><?php echo $this->company->getAccountsDetails()->getRefDate(); ?></td></tr>
            <tr><td>Next Due</td><td><?php echo $this->company->getAccountsDetails()->getNextDueDate(); ?></td></tr>
            <tr><td>Overdue?</td><td><?php echo ($this->company->getAccountsDetails()->isOverdue() ? 'Yes' : 'No'); ?></td></tr>
            <tr><td>Last Made Up</td><td><?php echo $this->company->getAccountsDetails()->getLastMadeUpDate(); ?></td></tr>
            <tr><td>Document available?</td><td><?php echo ($this->company->getAccountsDetails()->isDocumentAvailable() ? 'Yes' : 'No'); ?></td></tr>
        </table>
    </td>
</tr>

<tr>
    <td>Returns</td>
    <td>
        <table>
            <tr><td>Next Due</td><td><?php echo $this->company->getReturnDetails()->getNextDueDate(); ?></td></tr>
            <tr><td>Overdue?</td><td><?php echo ($this->company->getReturnDetails()->isOverdue() ? 'Yes' : 'No'); ?></td></tr>
            <tr><td>Last Made Up</td><td><?php echo $this->company->getReturnDetails()->getLastMadeUpDate(); ?></td></tr>
            <tr><td>Document available?</td><td><?php echo ($this->company->getReturnDetails()->isDocumentAvailable() ? 'Yes' : 'No'); ?></td></tr>
        </table>
    </td>
</tr>

<tr><td>Appointments</td>
<td>
    <?php 
        foreach ($this->appointments->getAppointments() as $person) {
            echo $person->getSurname() . '<br>';
    }?>
</td></tr>

</table>
