
<!-- <div style="padding: 15px;">
    <div class="row">
        <img style="float: left; width: 400px; padding-right: 15px; margin-left: 25px;" src="img/brand/logo.png" class="img-responsive" />
    </div>
    <div class="row" style="margin-left: 0px; margin-top: 5px;"></div>
</div>-->


<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="jumbotron well">
			<p>
<img style="float: left; width: 400px; padding-right: 15px; " src="img/brand/logo.png" class="img-responsive" />
</p>

				<p style="clear:both">
				    Directorzone is a social networking portal for directors and investors.  A repository of company information, business contacts, news and events.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
			<div class="row clearfix">
				<div class="col-md-2 column">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">
								Movers
							</h3>
						</div>
						<div class="panel-body">
						
						</div>

					</div>
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">
								Talent pool
							</h3>
						</div>
						<div class="panel-body">
						
						</div>

					</div>
				</div>
				<div class="col-md-6 column">
					<ul class="nav nav-tabs">
						<li class="active">
							<a href="#" id="tab-companies">Companies</a>
						</li>
						<li>
							<a href="#" id="tab-people">People</a>
						</li>
						<li>
							<a href="#" id="tab-services">Services</a>
						</li>

					</ul>
					<table class="table table-striped table-bordered table-hover rowlink" data-link="row" id="directories">

							<tr>
								<th>
									Number
								</th>
								<th>
									Name
								</th>
								<th>
									Exchange
								</th>
							</tr>

					</table>
					
					<ul class="pager">
                    <li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
                    <li class="next" id="next"><a href="#">Next &rarr;</a></li>
                    </ul>
				</div>
				<div class="col-md-4 column">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">
								News
							</h3>
						</div>
						<div class="panel-body">
							
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">
								Wanted / Offered
							</h3>
						</div>
						<div class="panel-body">
			
						</div>
						
					</div>
				</div>
			</div>
			<div class="row clearfix">
				<div class="col-md-6 column">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">
								Blog posts
							</h3>
						</div>
						<div class="panel-body">
				
						</div>

					</div>
				</div>
				<div class="col-md-6 column">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">
								Meeting requests
							</h3>
						</div>
						<div class="panel-body">
			
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>

$(document).ready(function() {

	loadCompanies();
	
	$(document).delegate('#tab-companies', 'click', function() {
		$('#tab-companies').parent().addClass('active');
		$('#tab-people').parent().removeClass('active');
		$('#tab-services').parent().removeClass('active');
		loadCompanies();
	});
	
	$(document).delegate('#tab-people', 'click', function() {
		$('#tab-companies').parent().removeClass('active');
		$('#tab-people').parent().addClass('active');
		$('#tab-services').parent().removeClass('active');
		loadPeople();
	});

	$(document).delegate('#tab-services', 'click', function() {
		$('#tab-people').parent().removeClass('active');
		$('#tab-companies').parent().removeClass('active');
		$('#tab-services').parent().addClass('active');
		loadServices();
	});

});

function loadCompanies()
{
	netsensia_Pager(
			1,
			5,
			'directories',
			'/ajax/company/list',
			function(key, value) {
				var url = '/directories/company/' + value.internalId;
				var newRow = '<tr>';
				newRow += '<td><a href="' + url + '">' + value.number + '</a></td>';
				newRow += '<td>' + value.name + '</td>';
				newRow += '<td>FTSE AIM 100</td>';
				newRow += '</tr>';
		
				return newRow;
			}
		);
}

function loadPeople()
{
	netsensia_Pager(
			1,
			5,
			'directories',
			'/ajax/people/list',
			function(key, value) {
				var newRow = '<tr>';
				newRow += '<td>' + value.name + '</td>';
				newRow += '<td>' + value.companyname + '</td>';
				newRow += '<td>' + value.appointmenttype + '</td>';
				newRow += '</tr>';
		
				return newRow;
			}
		);	
}

function loadServices()
{
	loadCompanies();
}


</script>