           <!--  <div class="container">
            		<div style="margin-bottom:10px">
	     <div class="visible-lg">  
                <div style="width:1140px;height:120px;border:1px solid #000;text-align:center; background-color:green"><br><span style="position:relative;top:12px; color:white; font-size:2em;">I am a banner ad and I will be seen on large displays such as a desktop computer</span></div>  
         </div> 
         
		 <div class="visible-md">  
                <div style="width:940px;height:90px;border:1px solid #000;text-align:center; background-color:green"><br><span style="position:relative;top:2px; color:white; font-size:2em;">I am a banner ad and I will be seen on medium displays such as tablets</span></div>  
         </div> 
         
         		 <div class="visible-sm">  
                <div style="width:720px;height:75px;border:1px solid #000;text-align:center; background-color:green"><br><span style="position:relative;top:0px; color:white; font-size:1.5em;">I am a banner ad and I will be seen on small displays such as phones</span></div>  
         </div> 
         
         		 <div class="visible-xs">  
                <div style="width:340px;height:65px;border:1px solid #000;text-align:center; background-color:green"><br><span style="position:relative;top:0px; color:white; font-size:1.1em;"><span style="color:white">Advert. I will be seen on extra small displays</span></div>  
         </div> 
         </div>
         </div>-->
         
         <div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
		


			<div class="row clearfix">
				<div class="col-md-3 column">
					<?php $this->NewsPanel('Movers', $this->mediaItems[8], 'panel-info'); ?>
					<?php $this->NewsPanel('Offered', $this->mediaItems[4], 'panel-danger'); ?>
				</div>
				<div class="col-md-6 column">
					<ul class="nav nav-tabs">
						<li class="active">
							<a href="#" id="tab-companies">Companies</a>
						</li>
						<li>
							<a href="#" id="tab-people">People</a>
						</li>
						<li>
							<a href="#" id="tab-services">Accelerators</a>
						</li>
					</ul>
					<table class="table table-striped table-bordered table-hover rowlink" data-link="row" id="directories">
                            
							<tr>
								<th>
									<a class="columnHeading" data-column-number="1">Number</a>
								</th>
								<th>
									<a class="columnHeading" data-column-number="2">Name</a>
								</th>
								<th>
									<a class="columnHeading" data-column-number="3">Exchange</a>
								</th>
							</tr>

					</table>
					
					<ul class="pager">
                    <li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
                    <li class="next" id="next"><a href="#">Next &rarr;</a></li>
                    </ul>
				</div>
				<div class="col-md-3 column">
					<?php $this->NewsPanel('News', $this->mediaItems[2], 'panel-info'); ?>
					<?php $this->NewsPanel('Wanted', $this->mediaItems[3], 'panel-danger'); ?>

				</div>
			</div>
			<div class="row clearfix">
				<div class="col-md-6 column">
					<?php $this->NewsPanel('Member Articles', $this->mediaItems[1], 'panel-info'); ?>
				</div>
				<div class="col-md-6 column">
					<?php $this->NewsPanel('Events', $this->mediaItems[5], 'panel-info'); ?>
				</div>
			</div>
		</div>
	</div>
</div>

<script>

$(document).ready(function() {

	loadCompanies(false);

	$(document).delegate('.columnHeading', 'click', function() {
		var currentTab = $('#columnSorter').attr('data-tab');
		switch (currentTab) {
		case "1":
			loadCompanies('L');
			break;
		case "2":
			loadPeople();
			break;
		case "3":
			loadCompanies('S');
			break;
		}
	});
	
	$(document).delegate('#tab-companies', 'click', function() {
		$('#tab-companies').parent().addClass('active');
		$('#tab-people').parent().removeClass('active');
		$('#tab-services').parent().removeClass('active');
		$('#columnSorter').attr('data-tab', 1);
		loadCompanies('L');
	});
	
	$(document).delegate('#tab-people', 'click', function() {
		$('#tab-companies').parent().removeClass('active');
		$('#tab-people').parent().addClass('active');
		$('#tab-services').parent().removeClass('active');
		$('#columnSorter').attr('data-tab', 2);
		loadPeople();
	});

	$(document).delegate('#tab-services', 'click', function() {
		$('#tab-companies').parent().removeClass('active');
		$('#tab-people').parent().removeClass('active');
		$('#tab-services').parent().addClass('active');
		$('#columnSorter').attr('data-tab', 3);
		loadCompanies('S');
	});

});

function loadCompanies(type)
{

	netsensia_Pager(
			1,
			12,
			'directories',
			'/ajax/company/list?type=' + type,
			function(key, value) {
				var url = '/directories/company/' + value.internalId;
				var newRow = '<tr>';
				newRow += '<td><a href="' + url + '">' + value.number + '</a></td>';
				newRow += '<td>' + value.name + '</td>';
				newRow += '<td>FTSE AIM 100</td>';
				newRow += '</tr>';
		
				return newRow;
			}
		);
}

function loadPeople()
{
	netsensia_Pager(
			1,
			12,
			'directories',
			'/ajax/people/list',
			function(key, value) {
				var url = '/directories/people/' + value.internalId;
				var newRow = '<tr>';
				newRow += '<td><a href="' + url + '">' + value.name + '</a></td>';
				newRow += '<td>' + value.companyname + '</td>';
				newRow += '<td>' + value.appointmenttype + '</td>';
				newRow += '</tr>';
		
				return newRow;
			}
		);	
}

</script>