
         
         <div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
		


			<div class="row clearfix">
				<div class="col-md-3 column">
					<?php $this->NewsPanel('News', $this->mediaItems[2], 'panel-info'); ?>
					<?php $this->NewsPanel('Movers', $this->mediaItems[8], 'panel-info'); ?>
				</div>
				<div class="col-md-6 column">
					<ul class="nav nav-tabs">
						<li class="active">
							<a href="#" id="tab-companies">Companies</a>
						</li>
						<li>
							<a href="#" id="tab-people">People</a>
						</li>
						<li>
							<a href="#" id="tab-services">Accelerators</a>
						</li>
					</ul>
					<table class="table table-striped table-bordered table-hover rowlink" data-link="row" id="directories">
                    <caption>Sort by <a class="columnHeading fixed-order" data-column-number="-1">newest</a> | <a class="columnHeading fixed-order" data-column-number="1">oldest</a></caption>        
							<tr>
								<th>
									<a class="columnHeading" data-column-number="2">Number</a>
								</th>
								<th>
									<a class="columnHeading" data-column-number="3">Name</a>
								</th>
								<th>
									<a class="columnHeading" data-column-number="4">Exchange</a>
								</th>
							</tr>

					</table>
					
					<ul class="pager">
                    <li class="previous" id="previous" class="disabled"><a href="#">&larr; Previous</a></li>
                    <li class="next" id="next"><a href="#">Next &rarr;</a></li>
                    </ul>
				</div>
				<div class="col-md-3 column">
					<?php $this->NewsPanel('Offered', $this->mediaItems[4], 'panel-danger'); ?>
					<?php $this->NewsPanel('Wanted', $this->mediaItems[3], 'panel-danger'); ?>
				</div>
			</div>
								
			
			<div class="row clearfix">
				<div class="col-md-3 column">
				    <?php $this->NewsPanel('Events', $this->mediaItems[5], 'panel-info'); ?>
				</div>
				<div class="col-md-3 column">
				    <?php $this->NewsPanel('Member Articles', $this->mediaItems[1], 'panel-info'); ?>
				</div>
				<div class="col-md-3 column">
				    <?php $this->NewsPanel('Meeting Requests', $this->mediaItems[6], 'panel-danger'); ?>
				</div>
				<div class="col-md-3 column">
					<?php $this->NewsPanel('Jobs', $this->mediaItems[7], 'panel-danger'); ?>
				</div>
			</div>
		</div>
	</div>
</div>

<script>

$(document).ready(function() {

	$('#columnSorter').attr('data-sort-by-column', '-1');
	
	loadCompanies('L');

	$(document).delegate('.columnHeading', 'click', function() {
		var currentTab = $('#columnSorter').attr('data-tab');
		switch (currentTab) {
		case "1":
			loadCompanies('L');
			break;
		case "2":
			loadPeople();
			break;
		case "3":
			loadCompanies('S');
			break;
		}
	});
	
	$(document).delegate('#tab-companies', 'click', function() {
		$('#tab-companies').parent().addClass('active');
		$('#tab-people').parent().removeClass('active');
		$('#tab-services').parent().removeClass('active');
		$('#columnSorter').attr('data-tab', 1);
		loadCompanies('L');
	});
	
	$(document).delegate('#tab-people', 'click', function() {
		$('#tab-companies').parent().removeClass('active');
		$('#tab-people').parent().addClass('active');
		$('#tab-services').parent().removeClass('active');
		$('#columnSorter').attr('data-tab', 2);
		loadPeople();
	});

	$(document).delegate('#tab-services', 'click', function() {
		$('#tab-companies').parent().removeClass('active');
		$('#tab-people').parent().removeClass('active');
		$('#tab-services').parent().addClass('active');
		$('#columnSorter').attr('data-tab', 3);
		loadCompanies('S');
	});

});

function loadCompanies(type)
{

	netsensia_Pager(
			1,
			14,
			'directories',
			'/ajax/company/list?type=' + type,
			function(key, value) {
				var url = '/directories/company/' + value.internalId;
				var newRow = '<tr>';
				newRow += '<td><a href="' + url + '">' + value.number + '</a></td>';
				newRow += '<td>' + value.name + '</td>';
				newRow += '<td>FTSE AIM 100</td>';
				newRow += '</tr>';
		
				return newRow;
			}
		);
}

function loadPeople()
{
	netsensia_Pager(
			1,
			12,
			'directories',
			'/ajax/people/list',
			function(key, value) {
				var url = '/directories/people/' + value.internalId;
				var newRow = '<tr>';
				newRow += '<td><a href="' + url + '">' + value.name + '</a></td>';
				newRow += '<td>' + value.companyname + '</td>';
				newRow += '<td>' + value.appointmenttype + '</td>';
				newRow += '</tr>';
		
				return newRow;
			}
		);	
}

</script>